// suites-handle.ts

import { make_livemap_core } from "hson-live";
import type { TestSuite } from "../../app/demos/test/tests.types";
import { snapCase, setCase, setManyCase, setManyFeedCase, deleteCase, deleteFeedCase, updateCase, updateFeedCase, read_case, commitCase, throwCase, feedCase, linkCase, pathCopyCase, originalPathCase } from "./handle-helpers";

export type TestLiveMap = ReturnType<typeof make_livemap_core>;
export type TestHandle = ReturnType<TestLiveMap["at"]>;

export function livemap_suites_handle(): TestSuite {
  const SUITE = "livemap/handle";

  return {
    suite: SUITE,
    cases: [
      snapCase({
        suite: SUITE,
        name: "handle snap reads scoped path",
        input: { user: { name: "Ada" } },
        path: ["user", "name"],
        expected: "Ada",
      }),
      setCase({
        suite: SUITE,
        name: "handle set writes scoped path",
        input: { user: { name: "Ada" } },
        path: ["user", "name"],
        value: "Grace",
        expectedChanged: true,
        expectedRoot: { user: { name: "Grace" } },
      }),
      setManyCase({
        suite: SUITE,
        name: "handle setMany writes multiple scoped properties",
        input: { user: { name: "Ada", role: "user" } },
        path: ["user"],
        values: { name: "Grace", role: "admin" },
        expectedChanged: true,
        expectedOps: [
          { kind: "set", path: ["user", "name"], prev: "Ada", next: "Grace" },
          { kind: "set", path: ["user", "role"], prev: "user", next: "admin" },
        ],
        expectedRoot: { user: { name: "Grace", role: "admin" } },
      }),
      setManyCase({
        suite: SUITE,
        name: "handle setMany omits unchanged properties",
        input: { user: { name: "Ada", role: "user" } },
        path: ["user"],
        values: { name: "Ada", role: "admin" },
        expectedChanged: true,
        expectedOps: [
          { kind: "set", path: ["user", "role"], prev: "user", next: "admin" },
        ],
        expectedRoot: { user: { name: "Ada", role: "admin" } },
      }),
      setManyFeedCase({
        suite: SUITE,
        name: "handle setMany emits feed events",
        input: { user: { name: "Ada", role: "user" } },
        path: ["user"],
        values: { name: "Grace", role: "admin" },
        expectedEvents: [
          {
            path: ["user"],
            value: { name: "Grace", role: "admin" },
            opPath: ["user", "name"],
            opPrev: "Ada",
            opNext: "Grace",
          },
        ],
      }),
      deleteCase({
        suite: SUITE,
        name: "handle delete removes scoped property",
        input: { user: { name: "Ada", role: "user" } },
        path: ["user", "name"],
        expectedChanged: true,
        expectedOps: [
          { kind: "delete", path: ["user", "name"], prev: "Ada", next: undefined },
        ],
        expectedRoot: { user: { role: "user" } },
      }),
      throwCase({
        suite: SUITE,
        name: "handle delete missing property throws",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user", "role"]).delete(),
        expectedMessage: "LiveMap delete path does not resolve: [\"user\", \"role\"]",
      }),
      deleteFeedCase({
        suite: SUITE,
        name: "handle delete emits feed event",
        input: { user: { name: "Ada", role: "user" } },
        path: ["user", "name"],
        expectedEvents: [
          {
            path: ["user", "name"],
            value: undefined,
            opPath: ["user", "name"],
            opPrev: "Ada",
            opNext: undefined,
          },
        ],
      }),
      updateCase({
        suite: SUITE,
        name: "handle update changes primitive",
        input: { count: 1 },
        path: ["count"],
        update: (value) => typeof value === "number" ? value + 1 : 1,
        expectedChanged: true,
        expectedRoot: { count: 2 },
      }),
      throwCase({
        suite: SUITE,
        name: "handle update missing property throws",
        input: { user: {} },
        act: (map) => map.at(["user", "name"]).update((value) => value ?? "Ada"),
        expectedMessage: "LiveMap set path does not resolve: [\"user\", \"name\"]",
      }),
      updateCase({
        suite: SUITE,
        name: "handle update unchanged produces empty ops",
        input: { user: { name: "Ada" } },
        path: ["user", "name"],
        update: (value) => value ?? "Grace",
        expectedChanged: false,
        expectedRoot: { user: { name: "Ada" } },
      }),
      updateFeedCase({
        suite: SUITE,
        name: "handle update emits feed event",
        input: { count: 1 },
        path: ["count"],
        update: (value) => typeof value === "number" ? value + 1 : 1,
        expectedEvents: [
          {
            path: ["count"],
            value: 2,
            opPath: ["count"],
            opPrev: 1,
            opNext: 2,
          },
        ],
      }),
      read_case({
        suite: SUITE,
        name: "handle array.is returns true for array",
        input: { items: [0, 1] },
        act: (map) => map.at(["items"]).array.is(),
        expected: true,
      }),
      read_case({
        suite: SUITE,
        name: "handle array.is returns false for non-array",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).array.is(),
        expected: false,
      }),
      read_case({
        suite: SUITE,
        name: "handle object.is returns true for object",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).object.is(),
        expected: true,
      }),
      read_case({
        suite: SUITE,
        name: "handle object.is returns false for non-object",
        input: { items: [0, 1] },
        act: (map) => map.at(["items"]).object.is(),
        expected: false,
      }),
      commitCase({
        suite: SUITE,
        name: "handle array.insert writes scoped array",
        input: { items: [0, 1, 3] },
        act: (map) => map.at(["items"]).array.insert(2, 2),
        expectedChanged: true,
        expectedOps: [
          { kind: "splice", path: ["items"], start: 2, removed: [], inserted: [2], prev: [0, 1, 3], next: [0, 1, 2, 3] },
        ],
        expectedRoot: { items: [0, 1, 2, 3] },
      }),
      commitCase({
        suite: SUITE,
        name: "handle array.remove writes scoped array",
        input: { items: [0, 1, 2] },
        act: (map) => map.at(["items"]).array.remove(1),
        expectedChanged: true,
        expectedOps: [
          { kind: "splice", path: ["items"], start: 1, removed: [1], inserted: [], prev: [0, 1, 2], next: [0, 2] },
        ],
        expectedRoot: { items: [0, 2] },
      }),
      commitCase({
        suite: SUITE,
        name: "handle array.replace writes scoped array",
        input: { items: [0, 1, 2] },
        act: (map) => map.at(["items"]).array.replace(1, 9),
        expectedChanged: true,
        expectedOps: [
          { kind: "splice", path: ["items"], start: 1, removed: [1], inserted: [9], prev: [0, 1, 2], next: [0, 9, 2] },
        ],
        expectedRoot: { items: [0, 9, 2] },
      }),
      commitCase({
        suite: SUITE,
        name: "handle array.move writes scoped array",
        input: { items: [0, 1, 2, 3, 4, 5] },
        act: (map) => map.at(["items"]).array.move(0, 3),
        expectedChanged: true,
        expectedOps: [
          { kind: "set", path: ["items"], prev: [0, 1, 2, 3, 4, 5], next: [1, 2, 3, 0, 4, 5] },
        ],
        expectedRoot: { items: [1, 2, 3, 0, 4, 5] },
      }),
      commitCase({
        suite: SUITE,
        name: "handle array.move moves item backward",
        input: { items: [0, 1, 2, 3, 4, 5] },
        act: (map) => map.at(["items"]).array.move(4, 1),
        expectedChanged: true,
        expectedOps: [
          { kind: "set", path: ["items"], prev: [0, 1, 2, 3, 4, 5], next: [0, 4, 1, 2, 3, 5] },
        ],
        expectedRoot: { items: [0, 4, 1, 2, 3, 5] },
      }),
      throwCase({
        suite: SUITE,
        name: "handle array bad index throws",
        input: { items: [0, 1] },
        act: (map) => map.at(["items"]).array.insert(4, 2),
        expectedMessage: "LiveMap array index does not resolve: [\"items\"][4]",
      }),
      throwCase({
        suite: SUITE,
        name: "handle array operation on non-array throws",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).array.insert(0, "x"),
        expectedMessage: "LiveMap path is not an array: [\"user\"]",
      }),
      feedCase({
        suite: SUITE,
        name: "handle array.insert emits feed event",
        input: { items: [0, 2] },
        path: ["items"],
        act: (handle) => handle.array.insert(1, 1),
        expectedEvents: [
          {
            path: ["items"],
            value: [0, 1, 2],
            opPath: ["items"],
            opPrev: [0, 2],
            opNext: [0, 1, 2],
          },
        ],
      }),
      linkCase({
        suite: SUITE,
        name: "handle array.move propagates link target",
        input: { source: [0, 1, 2, 3], target: [] },
        sourcePath: ["source"],
        targetPath: ["target"],
        act: (source) => source.array.move(0, 2),
        expectedRoot: { source: [1, 2, 0, 3], target: [1, 2, 0, 3] },
      }),
      commitCase({
        suite: SUITE,
        name: "handle object.setKey adds scoped key",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).object.setKey("role", "user"),
        expectedChanged: true,
        expectedOps: [
          { kind: "set", path: ["user", "role"], prev: undefined, next: "user" },
        ],
        expectedRoot: { user: { name: "Ada", role: "user" } },
      }),
      commitCase({
        suite: SUITE,
        name: "handle object.setKey replaces scoped key",
        input: { user: { name: "Ada", role: "user" } },
        act: (map) => map.at(["user"]).object.setKey("role", "admin"),
        expectedChanged: true,
        expectedOps: [
          { kind: "set", path: ["user", "role"], prev: "user", next: "admin" },
        ],
        expectedRoot: { user: { name: "Ada", role: "admin" } },
      }),
      feedCase({
        suite: SUITE,
        name: "handle object.setKey emits feed event",
        input: { user: { name: "Ada" } },
        path: ["user"],
        act: (handle) => handle.object.setKey("role", "user"),
        expectedEvents: [
          {
            path: ["user"],
            value: { name: "Ada", role: "user" },
            opPath: ["user", "role"],
            opPrev: undefined,
            opNext: "user",
          },
        ],
      }),
      linkCase({
        suite: SUITE,
        name: "handle object.setKey propagates link target",
        input: { source: { name: "Ada" }, target: {} },
        sourcePath: ["source"],
        targetPath: ["target"],
        act: (source) => source.object.setKey("role", "user"),
        expectedRoot: { source: { name: "Ada", role: "user" }, target: { name: "Ada", role: "user" } },
      }),
      throwCase({
        suite: SUITE,
        name: "handle object.setKey on non-object throws",
        input: { items: [0, 1] },
        act: (map) => map.at(["items"]).object.setKey("role", "user"),
        expectedMessage: "LiveMap path is not an object: [\"items\"]",
      }),
      commitCase({
        suite: SUITE,
        name: "handle object.deleteKey removes scoped key",
        input: { user: { name: "Ada", role: "user" } },
        act: (map) => map.at(["user"]).object.deleteKey("role"),
        expectedChanged: true,
        expectedOps: [
          { kind: "delete", path: ["user", "role"], prev: "user", next: undefined },
        ],
        expectedRoot: { user: { name: "Ada" } },
      }),
      commitCase({
        suite: SUITE,
        name: "handle object.deleteKey missing key unchanged",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).object.deleteKey("role"),
        expectedChanged: false,
        expectedOps: [],
        expectedRoot: { user: { name: "Ada" } },
      }),
      feedCase({
        suite: SUITE,
        name: "handle object.deleteKey emits feed event",
        input: { user: { name: "Ada", role: "user" } },
        path: ["user"],
        act: (handle) => handle.object.deleteKey("role"),
        expectedEvents: [
          {
            path: ["user"],
            value: { name: "Ada" },
            opPath: ["user", "role"],
            opPrev: "user",
            opNext: undefined,
          },
        ],
      }),
      linkCase({
        suite: SUITE,
        name: "handle object.deleteKey propagates link target",
        input: { source: { name: "Ada", role: "user" }, target: {} },
        sourcePath: ["source"],
        targetPath: ["target"],
        act: (source) => source.object.deleteKey("role"),
        expectedRoot: { source: { name: "Ada" }, target: { name: "Ada" } },
      }),
      throwCase({
        suite: SUITE,
        name: "handle object operation on non-object throws",
        input: { items: [0, 1] },
        act: (map) => map.at(["items"]).object.deleteKey("role"),
        expectedMessage: "LiveMap path is not an object: [\"items\"]",
      }),
      commitCase({
        suite: SUITE,
        name: "handle object.renameKey renames scoped key",
        input: { user: { name: "Ada", role: "user" } },
        act: (map) => map.at(["user"]).object.renameKey("role", "kind"),
        expectedChanged: true,
        expectedOps: [
          { kind: "replace", path: ["user"], prev: { name: "Ada", role: "user" }, next: { name: "Ada", kind: "user" } },
        ],
        expectedRoot: { user: { name: "Ada", kind: "user" } },
      }),
      commitCase({
        suite: SUITE,
        name: "handle object.renameKey missing key unchanged",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).object.renameKey("role", "kind"),
        expectedChanged: false,
        expectedOps: [],
        expectedRoot: { user: { name: "Ada" } },
      }),
      commitCase({
        suite: SUITE,
        name: "handle object.renameKey same key unchanged",
        input: { user: { name: "Ada", role: "user" } },
        act: (map) => map.at(["user"]).object.renameKey("role", "role"),
        expectedChanged: false,
        expectedOps: [],
        expectedRoot: { user: { name: "Ada", role: "user" } },
      }),
      commitCase({
        suite: SUITE,
        name: "handle object.renameKey overwrites existing key",
        input: { user: { name: "Ada", role: "user", kind: "person" } },
        act: (map) => map.at(["user"]).object.renameKey("role", "kind"),
        expectedChanged: true,
        expectedOps: [
          { kind: "replace", path: ["user"], prev: { name: "Ada", role: "user", kind: "person" }, next: { name: "Ada", kind: "user" } },
        ],
        expectedRoot: { user: { name: "Ada", kind: "user" } },
      }),
      feedCase({
        suite: SUITE,
        name: "handle object.renameKey emits feed event",
        input: { user: { name: "Ada", role: "user" } },
        path: ["user"],
        act: (handle) => handle.object.renameKey("role", "kind"),
        expectedEvents: [
          {
            path: ["user"],
            value: { name: "Ada", kind: "user" },
            opPath: ["user"],
            opPrev: { name: "Ada", role: "user" },
            opNext: { name: "Ada", kind: "user" },
          },
        ],
      }),
      linkCase({
        suite: SUITE,
        name: "handle object.renameKey propagates link target",
        input: { source: { name: "Ada", role: "user" }, target: {} },
        sourcePath: ["source"],
        targetPath: ["target"],
        act: (source) => source.object.renameKey("role", "kind"),
        expectedRoot: { source: { name: "Ada", kind: "user" }, target: { name: "Ada", kind: "user" } },
      }),
      throwCase({
        suite: SUITE,
        name: "handle object.renameKey on non-object throws",
        input: { items: [0, 1] },
        act: (map) => map.at(["items"]).object.renameKey("role", "kind"),
        expectedMessage: "LiveMap path is not an object: [\"items\"]",
      }),
      pathCopyCase({
        suite: SUITE,
        name: "handle path returns copy",
        input: { user: { name: "Ada" } },
        path: ["user", "name"],
        mutateReturnedPathTo: ["user", "role"],
        expectedHandlePath: ["user", "name"],
      }),
      originalPathCase({
        suite: SUITE,
        name: "handle path is stable after original path mutates",
        input: { user: { name: "Ada", role: "user" } },
        path: ["user", "name"],
        mutateOriginalPathTo: ["user", "role"],
        value: "Grace",
        expectedRoot: { user: { name: "Grace", role: "user" } },
      }),
      commitCase({
        suite: SUITE,
        name: "handle object.setMany writes multiple scoped properties",
        input: { user: { name: "Ada", role: "user" } },
        act: (map) => map.at(["user"]).object.setMany({ name: "Grace", role: "admin" }),
        expectedChanged: true,
        expectedOps: [
          { kind: "set", path: ["user", "name"], prev: "Ada", next: "Grace" },
          { kind: "set", path: ["user", "role"], prev: "user", next: "admin" },
        ],
        expectedRoot: { user: { name: "Grace", role: "admin" } },
      }),
      commitCase({
        suite: SUITE,
        name: "handle object.setMany omits unchanged properties",
        input: { user: { name: "Ada", role: "user" } },
        act: (map) => map.at(["user"]).object.setMany({ name: "Ada", role: "admin" }),
        expectedChanged: true,
        expectedOps: [
          { kind: "set", path: ["user", "role"], prev: "user", next: "admin" },
        ],
        expectedRoot: { user: { name: "Ada", role: "admin" } },
      }),
      feedCase({
        suite: SUITE,
        name: "handle object.setMany emits feed events",
        input: { user: { name: "Ada", role: "user" } },
        path: ["user"],
        act: (handle) => handle.object.setMany({ name: "Grace", role: "admin" }),
        expectedEvents: [
          {
            path: ["user"],
            value: { name: "Grace", role: "admin" },
            opPath: ["user", "name"],
            opPrev: "Ada",
            opNext: "Grace",
          },
        ],
      }),
      linkCase({
        suite: SUITE,
        name: "handle object.setMany propagates link target",
        input: { source: { name: "Ada", role: "user" }, target: {} },
        sourcePath: ["source"],
        targetPath: ["target"],
        act: (source) => source.object.setMany({ name: "Grace", role: "admin" }),
        expectedRoot: { source: { name: "Grace", role: "admin" }, target: { name: "Grace", role: "admin" } },
      }),
      throwCase({
        suite: SUITE,
        name: "handle object.setMany on non-object throws",
        input: { items: [0, 1] },
        act: (map) => map.at(["items"]).object.setMany({ role: "user" }),
        expectedMessage: "LiveMap path is not an object: [\"items\"]",
      }),
      commitCase({
        suite: SUITE,
        name: "handle array.push appends scoped array",
        input: { items: [0, 1] },
        act: (map) => map.at(["items"]).array.push(2),
        expectedChanged: true,
        expectedOps: [
          { kind: "splice", path: ["items"], start: 2, removed: [], inserted: [2], prev: [0, 1], next: [0, 1, 2] },
        ],
        expectedRoot: { items: [0, 1, 2] },
      }),
      feedCase({
        suite: SUITE,
        name: "handle array.push emits feed event",
        input: { items: [0, 1] },
        path: ["items"],
        act: (handle) => handle.array.push(2),
        expectedEvents: [
          {
            path: ["items"],
            value: [0, 1, 2],
            opPath: ["items"],
            opPrev: [0, 1],
            opNext: [0, 1, 2],
          },
        ],
      }),
      linkCase({
        suite: SUITE,
        name: "handle array.push propagates link target",
        input: { source: [0, 1], target: [] },
        sourcePath: ["source"],
        targetPath: ["target"],
        act: (source) => source.array.push(2),
        expectedRoot: { source: [0, 1, 2], target: [0, 1, 2] },
      }),
      throwCase({
        suite: SUITE,
        name: "handle array.push on non-array throws",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).array.push("x"),
        expectedMessage: "LiveMap path is not an array: [\"user\"]",
      }),
      throwCase({
        suite: SUITE,
        name: "handle array.push rejects non-JSON value",
        input: { items: [] },
        act: (map) => map.at(["items"]).array.push(undefined as never),
        expectedMessage: "LiveMap value is not JSON at [\"items\", 0]",
      }),
      commitCase({
        suite: SUITE,
        name: "handle array.unshift prepends scoped array",
        input: { items: [1, 2] },
        act: (map) => map.at(["items"]).array.unshift(0),
        expectedChanged: true,
        expectedOps: [
          { kind: "splice", path: ["items"], start: 0, removed: [], inserted: [0], prev: [1, 2], next: [0, 1, 2] },
        ],
        expectedRoot: { items: [0, 1, 2] },
      }),
      feedCase({
        suite: SUITE,
        name: "handle array.unshift emits feed event",
        input: { items: [1, 2] },
        path: ["items"],
        act: (handle) => handle.array.unshift(0),
        expectedEvents: [
          {
            path: ["items"],
            value: [0, 1, 2],
            opPath: ["items"],
            opPrev: [1, 2],
            opNext: [0, 1, 2],
          },
        ],
      }),
      linkCase({
        suite: SUITE,
        name: "handle array.unshift propagates link target",
        input: { source: [1, 2], target: [] },
        sourcePath: ["source"],
        targetPath: ["target"],
        act: (source) => source.array.unshift(0),
        expectedRoot: { source: [0, 1, 2], target: [0, 1, 2] },
      }),
      throwCase({
        suite: SUITE,
        name: "handle array.unshift on non-array throws",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).array.unshift("x"),
        expectedMessage: "LiveMap path is not an array: [\"user\"]",
      }),
      throwCase({
        suite: SUITE,
        name: "handle array.unshift rejects non-JSON value",
        input: { items: [] },
        act: (map) => map.at(["items"]).array.unshift(undefined as never),
        expectedMessage: "LiveMap value is not JSON at [\"items\", 0]",
      }),
      commitCase({
        suite: SUITE,
        name: "handle array.pop removes last item",
        input: { items: [0, 1, 2] },
        act: (map) => map.at(["items"]).array.pop(),
        expectedChanged: true,
        expectedOps: [
          { kind: "splice", path: ["items"], start: 2, removed: [2], inserted: [], prev: [0, 1, 2], next: [0, 1] },
        ],
        expectedRoot: { items: [0, 1] },
      }),
      feedCase({
        suite: SUITE,
        name: "handle array.pop emits feed event",
        input: { items: [0, 1, 2] },
        path: ["items"],
        act: (handle) => handle.array.pop(),
        expectedEvents: [
          {
            path: ["items"],
            value: [0, 1],
            opPath: ["items"],
            opPrev: [0, 1, 2],
            opNext: [0, 1],
          },
        ],
      }),
      linkCase({
        suite: SUITE,
        name: "handle array.pop propagates link target",
        input: { source: [0, 1, 2], target: [] },
        sourcePath: ["source"],
        targetPath: ["target"],
        act: (source) => source.array.pop(),
        expectedRoot: { source: [0, 1], target: [0, 1] },
      }),
      throwCase({
        suite: SUITE,
        name: "handle array.pop on non-array throws",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).array.pop(),
        expectedMessage: "LiveMap path is not an array: [\"user\"]",
      }),
      throwCase({
        suite: SUITE,
        name: "handle array.pop on empty array throws",
        input: { items: [] },
        act: (map) => map.at(["items"]).array.pop(),
        expectedMessage: "LiveMap array index does not resolve: [\"items\"][-1]",
      }),
      commitCase({
        suite: SUITE,
        name: "handle array.shift removes first item",
        input: { items: [0, 1, 2] },
        act: (map) => map.at(["items"]).array.shift(),
        expectedChanged: true,
        expectedOps: [
          { kind: "splice", path: ["items"], start: 0, removed: [0], inserted: [], prev: [0, 1, 2], next: [1, 2] },
        ],
        expectedRoot: { items: [1, 2] },
      }),
      feedCase({
        suite: SUITE,
        name: "handle array.shift emits feed event",
        input: { items: [0, 1, 2] },
        path: ["items"],
        act: (handle) => handle.array.shift(),
        expectedEvents: [
          {
            path: ["items"],
            value: [1, 2],
            opPath: ["items"],
            opPrev: [0, 1, 2],
            opNext: [1, 2],
          },
        ],
      }),
      linkCase({
        suite: SUITE,
        name: "handle array.shift propagates link target",
        input: { source: [0, 1, 2], target: [] },
        sourcePath: ["source"],
        targetPath: ["target"],
        act: (source) => source.array.shift(),
        expectedRoot: { source: [1, 2], target: [1, 2] },
      }),
      throwCase({
        suite: SUITE,
        name: "handle array.shift on non-array throws",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).array.shift(),
        expectedMessage: "LiveMap path is not an array: [\"user\"]",
      }),
      throwCase({
        suite: SUITE,
        name: "handle array.shift on empty array throws",
        input: { items: [] },
        act: (map) => map.at(["items"]).array.shift(),
        expectedMessage: "LiveMap array index does not resolve: [\"items\"][0]",
      }),
      commitCase({
        suite: SUITE,
        name: "handle array.clear removes all items",
        input: { items: [0, 1, 2] },
        act: (map) => map.at(["items"]).array.clear(),
        expectedChanged: true,
        expectedOps: [
          { kind: "set", path: ["items"], prev: [0, 1, 2], next: [] },
        ],
        expectedRoot: { items: [] },
      }),
      commitCase({
        suite: SUITE,
        name: "handle array.clear on empty array unchanged",
        input: { items: [] },
        act: (map) => map.at(["items"]).array.clear(),
        expectedChanged: false,
        expectedOps: [],
        expectedRoot: { items: [] },
      }),
      feedCase({
        suite: SUITE,
        name: "handle array.clear emits feed event",
        input: { items: [0, 1, 2] },
        path: ["items"],
        act: (handle) => handle.array.clear(),
        expectedEvents: [
          {
            path: ["items"],
            value: [],
            opPath: ["items"],
            opPrev: [0, 1, 2],
            opNext: [],
          },
        ],
      }),
      linkCase({
        suite: SUITE,
        name: "handle array.clear propagates link target",
        input: { source: [0, 1, 2], target: ["x"] },
        sourcePath: ["source"],
        targetPath: ["target"],
        act: (source) => source.array.clear(),
        expectedRoot: { source: [], target: [] },
      }),
      throwCase({
        suite: SUITE,
        name: "handle array.clear on non-array throws",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).array.clear(),
        expectedMessage: "LiveMap path is not an array: [\"user\"]",
      }),
      commitCase({
        suite: SUITE,
        name: "handle object.clear removes all properties",
        input: { user: { name: "Ada", role: "user" } },
        act: (map) => map.at(["user"]).object.clear(),
        expectedChanged: true,
        expectedOps: [
          { kind: "replace", path: ["user"], prev: { name: "Ada", role: "user" }, next: {} },
        ],
        expectedRoot: { user: {} },
      }),
      commitCase({
        suite: SUITE,
        name: "handle object.clear on empty object unchanged",
        input: { user: {} },
        act: (map) => map.at(["user"]).object.clear(),
        expectedChanged: false,
        expectedOps: [],
        expectedRoot: { user: {} },
      }),
      feedCase({
        suite: SUITE,
        name: "handle object.clear emits feed event",
        input: { user: { name: "Ada", role: "user" } },
        path: ["user"],
        act: (handle) => handle.object.clear(),
        expectedEvents: [
          {
            path: ["user"],
            value: {},
            opPath: ["user"],
            opPrev: { name: "Ada", role: "user" },
            opNext: {},
          },
        ],
      }),
      linkCase({
        suite: SUITE,
        name: "handle object.clear propagates link target",
        input: { source: { name: "Ada", role: "user" }, target: { old: true } },
        sourcePath: ["source"],
        targetPath: ["target"],
        act: (source) => source.object.clear(),
        expectedRoot: { source: {}, target: {} },
      }),
      throwCase({
        suite: SUITE,
        name: "handle object.clear on non-object throws",
        input: { items: [0, 1] },
        act: (map) => map.at(["items"]).object.clear(),
        expectedMessage: "LiveMap path is not an object: [\"items\"]",
      }),
      read_case({
        suite: SUITE,
        name: "handle object.hasKey returns true for existing key",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).object.hasKey("name"),
        expected: true,
      }),
      read_case({
        suite: SUITE,
        name: "handle object.hasKey returns false for missing key",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).object.hasKey("role"),
        expected: false,
      }),
      throwCase({
        suite: SUITE,
        name: "handle object.hasKey on non-object throws",
        input: { items: [0, 1] },
        act: (map) => map.at(["items"]).object.hasKey("name"),
        expectedMessage: "LiveMap path is not an object: [\"items\"]",
      }),
      throwCase({
        suite: SUITE,
        name: "handle object.hasKey rejects non-string key",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).object.hasKey(0 as never),
        expectedMessage: "LiveMap object key is not a string at [\"user\"]",
      }),

      read_case({
        suite: SUITE,
        name: "handle array.length returns array length",
        input: { items: [0, 1, 2] },
        act: (map) => map.at(["items"]).array.length(),
        expected: 3,
      }),
      throwCase({
        suite: SUITE,
        name: "handle array.length on non-array throws",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).array.length(),
        expectedMessage: "LiveMap path is not an array: [\"user\"]",
      }),
      read_case({
        suite: SUITE,
        name: "handle object.keys returns object keys",
        input: { user: { name: "Ada", role: "user" } },
        act: (map) => map.at(["user"]).object.keys(),
        expected: ["name", "role"],
      }),
      read_case({
        suite: SUITE,
        name: "handle object.keys returns empty array for empty object",
        input: { user: {} },
        act: (map) => map.at(["user"]).object.keys(),
        expected: [],
      }),
      throwCase({
        suite: SUITE,
        name: "handle object.keys on non-object throws",
        input: { items: [0, 1] },
        act: (map) => map.at(["items"]).object.keys(),
        expectedMessage: "LiveMap path is not an object: [\"items\"]",
      }),
      read_case({
        suite: SUITE,
        name: "handle object.values returns object values",
        input: { user: { name: "Ada", role: "user" } },
        act: (map) => map.at(["user"]).object.values(),
        expected: ["Ada", "user"],
      }),
      read_case({
        suite: SUITE,
        name: "handle object.values returns empty array for empty object",
        input: { user: {} },
        act: (map) => map.at(["user"]).object.values(),
        expected: [],
      }),
      throwCase({
        suite: SUITE,
        name: "handle object.values on non-object throws",
        input: { items: [0, 1] },
        act: (map) => map.at(["items"]).object.values(),
        expectedMessage: "LiveMap path is not an object: [\"items\"]",
      }),
      read_case({
        suite: SUITE,
        name: "handle object.entries returns object entries",
        input: { user: { name: "Ada", role: "user" } },
        act: (map) => map.at(["user"]).object.entries(),
        expected: [["name", "Ada"], ["role", "user"]],
      }),
      read_case({
        suite: SUITE,
        name: "handle object.entries returns empty array for empty object",
        input: { user: {} },
        act: (map) => map.at(["user"]).object.entries(),
        expected: [],
      }),
      throwCase({
        suite: SUITE,
        name: "handle object.entries on non-object throws",
        input: { items: [0, 1] },
        act: (map) => map.at(["items"]).object.entries(),
        expectedMessage: "LiveMap path is not an object: [\"items\"]",
      }),
      read_case({
        suite: SUITE,
        name: "handle array.at returns indexed item",
        input: { items: ["a", "b", "c"] },
        act: (map) => map.at(["items"]).array.at(1),
        expected: "b",
      }),
      throwCase({
        suite: SUITE,
        name: "handle array.at rejects bad index",
        input: { items: ["a", "b"] },
        act: (map) => map.at(["items"]).array.at(4),
        expectedMessage: "LiveMap array index does not resolve: [\"items\"][4]",
      }),
      throwCase({
        suite: SUITE,
        name: "handle array.at on non-array throws",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).array.at(0),
        expectedMessage: "LiveMap path is not an array: [\"user\"]",
      }),
      read_case({
        suite: SUITE,
        name: "handle object.getKey returns existing value",
        input: { user: { name: "Ada", role: "user" } },
        act: (map) => map.at(["user"]).object.getKey("name"),
        expected: "Ada",
      }),
      read_case({
        suite: SUITE,
        name: "handle object.getKey returns undefined for missing key",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).object.getKey("role"),
        expected: undefined,
      }),
      throwCase({
        suite: SUITE,
        name: "handle object.getKey on non-object throws",
        input: { items: [0, 1] },
        act: (map) => map.at(["items"]).object.getKey("name"),
        expectedMessage: "LiveMap path is not an object: [\"items\"]",
      }),
      throwCase({
        suite: SUITE,
        name: "handle object.getKey rejects non-string key",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).object.getKey(0 as never),
        expectedMessage: "LiveMap object key is not a string at [\"user\"]",
      }),

    ] as const,
  };
}

