// suites-node.ts

import type { TestCase, TestSuite } from "../../app/demos/test/tests.types";
import { ELEM_TAG, OBJ_TAG } from "hson-live";
import { make_node_live_after_delete_case, make_node_live_after_set_case, make_node_parent_content_case, make_node_attrs_copy_case, make_node_set_attr_case, make_node_set_attrs_case, make_node_remove_attr_case, make_node_clear_attrs_case, make_node_existing_attrs_case, make_node_attr_missing_path_throw_case, make_node_attr_json_backed_throw_case, make_node_json_html_tag_name_case, make_node_children_case, make_node_child_lookup_case, make_node_must_child_throw_case, make_node_append_case, make_node_append_missing_path_throw_case, make_node_append_html_case, make_node_insert_child_case, make_node_insert_child_append_case, make_node_insert_child_bad_index_throw_case, make_node_insert_missing_path_throw_case, make_node_move_child_case, make_node_move_child_backward_case, make_node_move_child_bad_to_index_throw_case, make_node_move_child_bad_from_index_throw_case, make_node_move_missing_path_throw_case, make_node_remove_children_case, make_node_remove_child_case, make_node_remove_child_bad_index_throw_case, make_node_remove_missing_path_throw_case, make_node_replace_children_case, make_node_replace_child_case, make_node_replace_child_bad_index_throw_case, make_node_replace_missing_path_throw_case } from "./node-helpers";



const SUITE = "livemap/node-internals";

type ExpectedFailTestCase = TestCase & Readonly<{
  expected: "fail";
  expectedError?: Readonly<{
    message?: string;
    includes?: string;
  }>;
}>;

export function expected_fail_case(testCase: TestCase, expectedMessage: string): ExpectedFailTestCase {
  return {
    ...testCase,
    expected: "fail",
    expectedError: { message: expectedMessage },
  };
}

export function livemap_suites_node(): TestSuite {
  return {
    suite: SUITE,
    cases: [
      make_node_live_after_delete_case({
        suite: SUITE,
        name: "node handle reflects deleted path",
        input: { user: { name: "Ada", role: "user" } },
        path: ["user", "name"],
        deletePath: ["user", "name"],
        expectedInitialTag: "name",
        expectedAfterDelete: undefined,
      }),
      make_node_live_after_set_case({
        suite: SUITE,
        name: "node handle resolves after missing path is created",
        input: { user: { name: "Ada" } },
        path: ["user", "role"],
        setPath: ["user", "role"],
        value: "admin",
        expectedInitial: undefined,
        expectedAfterSetTag: "role",
      }),
      make_node_parent_content_case({
        suite: SUITE,
        name: "node handle parent content reflects child set",
        input: { user: { name: "Ada" } },
        path: ["user"],
        setPath: ["user", "role"],
        value: "admin",
        expectedInitialContentLength: 1,
        expectedAfterSetContentLength: 1,
      }),
      make_node_attrs_copy_case({
        suite: SUITE,
        name: "node attrs returns defensive copy",
        html: "<button>Press</button>",
        path: ["button"],
        setName: "class",
        setValue: "active",
        mutateName: "class",
        mutateValue: "mutated",
        expectedAttr: "active",
        expectedAttrs: { class: "active" },
      }),
      make_node_set_attr_case({
        suite: SUITE,
        name: "node setAttr writes one attr and chains",
        html: "<button>Press</button>",
        path: ["button"],
        nameToSet: "class",
        valueToSet: "active",
        expectedAttr: "active",
        expectedAttrs: { class: "active" },
      }),
      make_node_set_attrs_case({
        suite: SUITE,
        name: "node setAttrs writes many attrs and preserves existing attrs",
        html: "<button>Press</button>",
        path: ["button"],
        firstName: "class",
        firstValue: "active",
        attrsToSet: { title: "Profile", hidden: true },
        expectedAttrs: { class: "active", title: "Profile", hidden: true },
      }),
      make_node_remove_attr_case({
        suite: SUITE,
        name: "node removeAttr removes one attr and chains",
        html: "<button>Press</button>",
        path: ["button"],
        attrsToSet: { class: "active", title: "Profile" },
        nameToRemove: "class",
        expectedRemovedAttr: undefined,
        expectedAttrs: { title: "Profile" },
      }),
      make_node_clear_attrs_case({
        suite: SUITE,
        name: "node clearAttrs removes all attrs and chains",
        html: "<button>Press</button>",
        path: ["button"],
        attrsToSet: { class: "active", title: "Profile" },
        expectedAttrs: {},
      }),
      make_node_existing_attrs_case({
        suite: SUITE,
        name: "node attrs reads parser-provided HTML attrs",
        html: `<button class="active" disabled>Press</button>`,
        path: ["button"],
        expectedClass: "active",
        expectedDisabled: "disabled",
        expectedAttrs: { class: "active", disabled: "disabled" },
      }),
      make_node_attr_missing_path_throw_case({
        suite: SUITE,
        name: "node attr mutation on missing path throws",
        input: { user: { name: "Ada" } },
        path: ["user", "role"],
        expectedMessage: "LiveMap node path does not resolve: [\"user\", \"role\"]",
      }),
      make_node_attr_json_backed_throw_case({
        suite: SUITE,
        name: "node attr mutation on JSON-backed path throws",
        input: { user: { name: "Ada" } },
        path: ["user"],
        expectedMessage: "LiveMap node attrs can only be edited on _hson_elem-backed nodes: [\"user\"]",
      }),
      make_node_json_html_tag_name_case({
        suite: SUITE,
        name: "node JSON key matching HTML tag remains JSON-backed",
        input: { button: { label: "Press" } },
        path: ["button"],
        expectedTag: "button",
        expectedContentLength: 1,
        expectedMessage: "LiveMap node attrs can only be edited on _hson_elem-backed nodes: [\"button\"]",
      }),
      make_node_children_case({
        suite: SUITE,
        name: "node children reads direct HSON child nodes",
        input: { user: { name: "Ada", role: "admin" } },
        path: ["user"],
        expectedChildTags: [OBJ_TAG],
        expectedMissingPathChildren: [],
      }),
      make_node_child_lookup_case({
        suite: SUITE,
        name: "node child lookup reads direct child by tag",
        input: { user: { name: "Ada", role: "admin" } },
        path: ["user"],
        tag: OBJ_TAG,
        missingTag: ELEM_TAG,
        expectedChildTag: OBJ_TAG,
        expectedChildrenByTagCount: 1,
        expectedMissingChildrenByTag: [],
        expectedMissingChild: undefined,
      }),
      make_node_must_child_throw_case({
        suite: SUITE,
        name: "node mustChild throws with path and tag context",
        input: { user: { name: "Ada" } },
        path: ["user"],
        missingTag: ELEM_TAG,
        expectedMessage: `LiveMap node child does not resolve: ["user"]."${ELEM_TAG}"`,
      }),
      make_node_append_case({
        suite: SUITE,
        name: "node append adds direct child and chains",
        input: { user: { name: "Ada" } },
        path: ["user"],
        childTag: "note",
        expectedChildTags: [OBJ_TAG, "note"],
        expectedAppendedTag: "note",
      }),
      make_node_append_missing_path_throw_case({
        suite: SUITE,
        name: "node append on missing path throws",
        input: { user: { name: "Ada" } },
        path: ["user", "role"],
        childTag: "note",
        expectedMessage: "LiveMap node path does not resolve: [\"user\", \"role\"]",
      }),
      make_node_append_html_case({
        suite: SUITE,
        name: "node append works on HTML-backed node",
        html: "<button>Press</button>",
        path: ["button"],
        childTag: "icon",
        expectedChildTags: [ELEM_TAG, "icon"],
        expectedAppendedTag: "icon",
      }),
            make_node_insert_child_case({
        suite: SUITE,
        name: "node insert.child inserts by child-node index and chains",
        input: { user: { name: "Ada" } },
        path: ["user"],
        firstAppendedTag: "note",
        secondAppendedTag: "icon",
        insertedTag: "badge",
        primitiveContent: "loose text",
        indexToInsert: 1,
        expectedBeforeChildTags: [OBJ_TAG, "note", "icon"],
        expectedAfterChildTags: [OBJ_TAG, "badge", "note", "icon"],
        expectedContentTagsAndValues: [OBJ_TAG, "loose text", "badge", "note", "icon"],
      }),
      make_node_insert_child_append_case({
        suite: SUITE,
        name: "node insert.child at child count appends",
        input: { user: { name: "Ada" } },
        path: ["user"],
        insertedTag: "badge",
        indexToInsert: 1,
        expectedChildTags: [OBJ_TAG, "badge"],
      }),
      make_node_insert_child_bad_index_throw_case({
        suite: SUITE,
        name: "node insert.child bad index throws",
        input: { user: { name: "Ada" } },
        path: ["user"],
        badIndex: 4,
        insertedTag: "badge",
        expectedMessage: "LiveMap node child index does not resolve: [\"user\"][4]",
      }),
      make_node_insert_missing_path_throw_case({
        suite: SUITE,
        name: "node insert on missing path throws",
        input: { user: { name: "Ada" } },
        path: ["user", "role"],
        insertedTag: "badge",
        expectedMessage: "LiveMap node path does not resolve: [\"user\", \"role\"]",
      }),
      make_node_move_child_case({
        suite: SUITE,
        name: "node move.child moves by child-node index and chains",
        input: { user: { name: "Ada" } },
        path: ["user"],
        firstAppendedTag: "note",
        secondAppendedTag: "icon",
        primitiveContent: "loose text",
        fromIndex: 0,
        toIndex: 2,
        expectedBeforeChildTags: [OBJ_TAG, "note", "icon"],
        expectedAfterChildTags: ["note", "icon", OBJ_TAG],
        expectedContentTagsAndValues: ["loose text", "note", "icon", OBJ_TAG],
      }),
      make_node_move_child_backward_case({
        suite: SUITE,
        name: "node move.child moves backward by child-node index",
        input: { user: { name: "Ada" } },
        path: ["user"],
        firstAppendedTag: "note",
        secondAppendedTag: "icon",
        fromIndex: 2,
        toIndex: 0,
        expectedBeforeChildTags: [OBJ_TAG, "note", "icon"],
        expectedAfterChildTags: ["icon", OBJ_TAG, "note"],
      }),
      make_node_move_child_bad_to_index_throw_case({
        suite: SUITE,
        name: "node move.child bad to index throws",
        input: { user: { name: "Ada" } },
        path: ["user"],
        fromIndex: 0,
        badToIndex: 4,
        expectedMessage: "LiveMap node child index does not resolve: [\"user\"][4]",
      }),
      make_node_move_child_bad_from_index_throw_case({
        suite: SUITE,
        name: "node move.child bad from index throws",
        input: { user: { name: "Ada" } },
        path: ["user"],
        badFromIndex: 4,
        toIndex: 0,
        expectedMessage: "LiveMap node child index does not resolve: [\"user\"][4]",
      }),
      make_node_move_missing_path_throw_case({
        suite: SUITE,
        name: "node move on missing path throws",
        input: { user: { name: "Ada" } },
        path: ["user", "role"],
        fromIndex: 0,
        toIndex: 0,
        expectedMessage: "LiveMap node path does not resolve: [\"user\", \"role\"]",
      }),
      make_node_remove_children_case({
        suite: SUITE,
        name: "node remove.children removes direct child nodes and chains",
        input: { user: { name: "Ada" } },
        path: ["user"],
        appendedTag: "note",
        primitiveContent: "loose text",
        expectedBeforeChildTags: [OBJ_TAG, "note"],
        expectedAfterChildTags: [],
        expectedAfterContent: ["loose text"],
      }),
      make_node_remove_child_case({
        suite: SUITE,
        name: "node remove.child removes by child-node index and chains",
        input: { user: { name: "Ada" } },
        path: ["user"],
        firstAppendedTag: "note",
        secondAppendedTag: "icon",
        primitiveContent: "loose text",
        indexToRemove: 1,
        expectedBeforeChildTags: [OBJ_TAG, "note", "icon"],
        expectedAfterChildTags: [OBJ_TAG, "icon"],
        expectedContentTagsAndValues: [OBJ_TAG, "loose text", "icon"],
      }),
      make_node_remove_child_bad_index_throw_case({
        suite: SUITE,
        name: "node remove.child bad index throws",
        input: { user: { name: "Ada" } },
        path: ["user"],
        badIndex: 4,
        expectedMessage: "LiveMap node child index does not resolve: [\"user\"][4]",
      }),
      make_node_remove_missing_path_throw_case({
        suite: SUITE,
        name: "node remove on missing path throws",
        input: { user: { name: "Ada" } },
        path: ["user", "role"],
        expectedMessage: "LiveMap node path does not resolve: [\"user\", \"role\"]",
      }),
      make_node_replace_children_case({
        suite: SUITE,
        name: "node replace.children replaces direct child nodes and chains",
        input: { user: { name: "Ada" } },
        path: ["user"],
        appendedTag: "note",
        replacementTags: ["icon", "badge"],
        primitiveContent: "loose text",
        expectedBeforeChildTags: [OBJ_TAG, "note"],
        expectedAfterChildTags: ["icon", "badge"],
        expectedAfterContent: ["loose text", "icon", "badge"],
      }),
      make_node_replace_child_case({
        suite: SUITE,
        name: "node replace.child replaces by child-node index and chains",
        input: { user: { name: "Ada" } },
        path: ["user"],
        firstAppendedTag: "note",
        secondAppendedTag: "icon",
        replacementTag: "badge",
        primitiveContent: "loose text",
        indexToReplace: 1,
        expectedBeforeChildTags: [OBJ_TAG, "note", "icon"],
        expectedAfterChildTags: [OBJ_TAG, "badge", "icon"],
        expectedContentTagsAndValues: [OBJ_TAG, "loose text", "badge", "icon"],
      }),
      make_node_replace_child_bad_index_throw_case({
        suite: SUITE,
        name: "node replace.child bad index throws",
        input: { user: { name: "Ada" } },
        path: ["user"],
        badIndex: 4,
        replacementTag: "badge",
        expectedMessage: "LiveMap node child index does not resolve: [\"user\"][4]",
      }),
      make_node_replace_missing_path_throw_case({
        suite: SUITE,
        name: "node replace on missing path throws",
        input: { user: { name: "Ada" } },
        path: ["user", "role"],
        replacementTag: "badge",
        expectedMessage: "LiveMap node path does not resolve: [\"user\", \"role\"]",
      }),
    ] as const,
  };
}


