/* Generated by Hson Schema hson-schema-mvp-6. Do not edit. */
import type { HsonNumber } from "hson-live";
import type { HsonCanonical } from "hson-live/hson";
abstract class __TOWL_SCHEMAD0ObjectProof0 { declare private readonly __hsonSchemaProof0: void; }
abstract class __TOWL_SCHEMAD0DefinitionProof1 { declare private readonly __hsonSchemaProof1: void; }
abstract class __TOWL_SCHEMARootM3IntR0Proof2 { declare private readonly __hsonSchemaProof2: void; }
abstract class __TOWL_SCHEMARootM3MinR1Proof3 { declare private readonly __hsonSchemaProof3: void; }
abstract class __TOWL_SCHEMARootM3MaxR2Proof4 { declare private readonly __hsonSchemaProof4: void; }
abstract class __TOWL_SCHEMARootM5IntR0Proof5 { declare private readonly __hsonSchemaProof5: void; }
abstract class __TOWL_SCHEMARootM5MinR1Proof6 { declare private readonly __hsonSchemaProof6: void; }
abstract class __TOWL_SCHEMARootObjectProof7 { declare private readonly __hsonSchemaProof7: void; }
abstract class __TOWL_SCHEMAHsonProof8 { declare private readonly __hsonSchemaProof8: void; }
type __TOWL_SCHEMADefinition0 = (Readonly<{ readonly sessionId: (string) | (null); readonly connected: boolean; readonly ready: boolean; }> & __TOWL_SCHEMAD0ObjectProof0) & __TOWL_SCHEMAD0DefinitionProof1;
export type TOWL_SCHEMAType = Readonly<{ readonly phase: string; readonly player1: __TOWL_SCHEMADefinition0; readonly player2: __TOWL_SCHEMADefinition0; readonly position: HsonNumber & __TOWL_SCHEMARootM3IntR0Proof2 & __TOWL_SCHEMARootM3MinR1Proof3 & __TOWL_SCHEMARootM3MaxR2Proof4; readonly winner: (string) | (null); readonly round: HsonNumber & __TOWL_SCHEMARootM5IntR0Proof5 & __TOWL_SCHEMARootM5MinR1Proof6; }> & __TOWL_SCHEMARootObjectProof7;
export type TOWL_SCHEMAHson = HsonCanonical & __TOWL_SCHEMAHsonProof8;
