/* Generated by Hson Schema hson-schema-mvp-7. Do not edit. */
import type { HsonNumber, HsonSchemaMutationCandidate } from "hson-live";
import type { HsonCanonical } from "hson-live/hson";
abstract class __TOWL_SCHEMAD0ObjectProof0 { declare private readonly __hsonSchemaProof0: void; }
abstract class __TOWL_SCHEMAD0DefinitionProof1 { declare private readonly __hsonSchemaProof1: void; }
abstract class __TOWL_SCHEMARootM3IntR0Proof2 { declare private readonly __hsonSchemaProof2: void; }
abstract class __TOWL_SCHEMARootM3MinR1Proof3 { declare private readonly __hsonSchemaProof3: void; }
abstract class __TOWL_SCHEMARootM3MaxR2Proof4 { declare private readonly __hsonSchemaProof4: void; }
abstract class __TOWL_SCHEMARootM5IntR0Proof5 { declare private readonly __hsonSchemaProof5: void; }
abstract class __TOWL_SCHEMARootM5MinR1Proof6 { declare private readonly __hsonSchemaProof6: void; }
abstract class __TOWL_SCHEMARootObjectProof7 { declare private readonly __hsonSchemaProof7: void; }
abstract class __TOWL_SCHEMAHsonProof8 { declare private readonly __hsonSchemaProof8: void; }
type __TOWL_SCHEMADefinition0MutationCandidate = { sessionId: (string) | (null); connected: boolean; ready: boolean; };
type __TOWL_SCHEMADefinition0 = (Readonly<{ readonly sessionId: (string) | (null); readonly connected: boolean; readonly ready: boolean; }> & __TOWL_SCHEMAD0ObjectProof0 & HsonSchemaMutationCandidate<{ sessionId: (string) | (null); connected: boolean; ready: boolean; }>) & __TOWL_SCHEMAD0DefinitionProof1 & HsonSchemaMutationCandidate<__TOWL_SCHEMADefinition0MutationCandidate>;
export type TOWL_SCHEMAType = Readonly<{ readonly phase: ("lobby") | (("ready") | (("playing") | ("finished"))); readonly player1: __TOWL_SCHEMADefinition0; readonly player2: __TOWL_SCHEMADefinition0; readonly position: HsonNumber & HsonSchemaMutationCandidate<number> & __TOWL_SCHEMARootM3IntR0Proof2 & HsonSchemaMutationCandidate<number> & __TOWL_SCHEMARootM3MinR1Proof3 & HsonSchemaMutationCandidate<number> & __TOWL_SCHEMARootM3MaxR2Proof4 & HsonSchemaMutationCandidate<number>; readonly winner: (("player1") | ("player2")) | (null); readonly round: HsonNumber & HsonSchemaMutationCandidate<number> & __TOWL_SCHEMARootM5IntR0Proof5 & HsonSchemaMutationCandidate<number> & __TOWL_SCHEMARootM5MinR1Proof6 & HsonSchemaMutationCandidate<number>; }> & __TOWL_SCHEMARootObjectProof7 & HsonSchemaMutationCandidate<{ phase: ("lobby") | (("ready") | (("playing") | ("finished"))); player1: __TOWL_SCHEMADefinition0MutationCandidate; player2: __TOWL_SCHEMADefinition0MutationCandidate; position: number; winner: (("player1") | ("player2")) | (null); round: number; }>;
export type TOWL_SCHEMAHson = HsonCanonical & __TOWL_SCHEMAHsonProof8;
