import { lstat, readdir, readFile } from "node:fs/promises";
import { join, resolve } from "node:path";
const safe=(p:unknown):p is string=>typeof p==="string"&&p.length>0&&!p.startsWith("/")&&!p.split("/").includes(".."); const statuses=new Set(["pass","fail","skip","unsupported","cancelled","error"]);
const forbidden=/\bBearer\s+(?!<redacted>)[A-Za-z0-9._~+\/-]+=*|\b(token|secret|password|credential)\s*[=:]\s*(?!<redacted>)|\/(?:Users|home)\/[A-Za-z0-9_.-]+/i;
export async function validate_run_site(runDir:string):Promise<void>{const site=join(runDir,"site"),root=resolve(site),seen=new Set<string>(),ids=new Set<string>();const load=async(file:string):Promise<Record<string,unknown>>=>{if(!safe(file)||seen.has(file))throw new Error(`SITE_REFERENCE_INVALID:${String(file)}`);const path=resolve(site,file);if(!path.startsWith(root+"/"))throw new Error("SITE_PATH_ESCAPE");const state=await lstat(path);if(state.isSymbolicLink()||!state.isFile()||state.size>32*1024*1024)throw new Error("SITE_UNSAFE_FILE");seen.add(file);const raw=await readFile(path,"utf8");if(forbidden.test(raw))throw new Error("PUBLIC_REDACTION_SURVIVED");const value:unknown=JSON.parse(raw);if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("SITE_JSON_SHAPE");return value as Record<string,unknown>};
 const index=await load("index.json");if(typeof index.id!=="string"||!statuses.has(String(index.status))||!Array.isArray(index.categories)||!Array.isArray(index.suites)||!index.totals||typeof index.totals!=="object")throw new Error("SITE_INDEX_SHAPE");
 for(const category of index.categories){if(!category||typeof category!=="object"||typeof (category as any).id!=="string"||!safe((category as any).file)||ids.has(`cat:${(category as any).id}`))throw new Error("SITE_CATEGORY_REF");ids.add(`cat:${(category as any).id}`);const value=await load((category as any).file);if(value.id!==(category as any).id||!Array.isArray(value.suites))throw new Error("SITE_CATEGORY_SHAPE")}
 const artifact=async(path:string)=>{if(!safe(path)||!path.startsWith("artifacts/")||seen.has(path))throw new Error("SITE_ARTIFACT_PATH");const full=resolve(site,path),state=await lstat(full);if(!full.startsWith(root+"/")||state.isSymbolicLink()||!state.isFile())throw new Error("SITE_ARTIFACT_PATH");seen.add(path)};
 for(const suiteRef of index.suites){if(!suiteRef||typeof suiteRef!=="object"||typeof (suiteRef as any).id!=="string"||!safe((suiteRef as any).file)||ids.has(`suite:${(suiteRef as any).id}`))throw new Error("SITE_SUITE_REF");ids.add(`suite:${(suiteRef as any).id}`);const suite=await load((suiteRef as any).file);if(suite.id!==(suiteRef as any).id||!Array.isArray(suite.cases)||!statuses.has(String(suite.status)))throw new Error("SITE_SUITE_SHAPE");for(const c of suite.cases){if(!c||typeof c!=="object"||typeof (c as any).id!=="string"||!safe((c as any).file)||ids.has(`case:${suite.id}:${(c as any).id}`))throw new Error("SITE_CASE_REF");ids.add(`case:${suite.id}:${(c as any).id}`);const value=await load((c as any).file);if(value.id!==(c as any).id||!statuses.has(String(value.status))||!Array.isArray(value.diagnostics)||!Array.isArray(value.artifacts))throw new Error("SITE_CASE_SHAPE");for(const a of value.artifacts as any[]){if(!a)throw new Error("SITE_ARTIFACT_PATH");await artifact(a.path)}}}
 for(const folder of ["categories","suites","cases","artifacts"])for(const entry of await readdir(join(site,folder)))if(!seen.has(`${folder}/${entry}`))throw new Error(`SITE_UNREFERENCED_FILE:${folder}/${entry}`);
}
