import { execFileSync } from "node:child_process";
import { randomUUID } from "node:crypto";
import { cwd } from "node:process";
import { copyFile, lstat, mkdir } from "node:fs/promises";
import { join, resolve, basename } from "node:path";
import type { TestEvent } from "../../core/test-contracts";
import { reduce_status } from "../../../../src/shared/testing/test-run-contract";
import { totals_for, type Diagnostic, type RunReport, type SuiteReport } from "./run-report-contract";
import { create_local_redactor, DIAGNOSTIC_RUN_BYTES, type LocalRedactor } from "./run-report-redaction";
import { materialize_run_site } from "./run-report-materializer";
import { begin_run, finalize_run } from "./run-report-storage";
import { TestEventAdapter } from "./test-event-adapter";
function repository(name:string,path:string){try{const revision=execFileSync("git",["-C",path,"rev-parse","HEAD"],{encoding:"utf8",stdio:["ignore","pipe","ignore"]}).trim(),dirty=execFileSync("git",["-C",path,"status","--porcelain"],{encoding:"utf8",stdio:["ignore","pipe","ignore"]}).trim().length>0;return {name,revision:/^[a-f0-9]{40}$/.test(revision)?revision:null,dirty}}catch{return {name,revision:null,dirty:null}}}
export class LocalRunReporter { readonly id=randomUUID();readonly started=new Date();readonly redactor:LocalRedactor;readonly adapter:TestEventAdapter;readonly diagnostics:Diagnostic[]=[]; constructor(readonly root=cwd(),readonly selection:Readonly<{profile:string|null;ids:readonly string[]}>={profile:null,ids:[]}){this.redactor=create_local_redactor(root);this.adapter=new TestEventAdapter(this.redactor)}
 event(event:TestEvent):void{try{this.adapter.ingest(event)}catch(error){this.add("reporter",error)}} private add(kind:string,error:unknown){const d=this.redactor.diagnostic(kind,error);const used=this.diagnostics.reduce((n,x)=>n+Buffer.byteLength(JSON.stringify(x)),0);if(used+Buffer.byteLength(JSON.stringify(d))<=DIAGNOSTIC_RUN_BYTES)this.diagnostics.push(d)}
 private report(suites:readonly SuiteReport[],forced?:"error"):RunReport{const ended=new Date(),status=forced??reduce_status(suites.map(s=>s.status)),cases=suites.flatMap(s=>s.cases),totals=totals_for(cases,suites);return {id:this.id,startedAt:this.started.toISOString(),endedAt:ended.toISOString(),durationMs:ended.getTime()-this.started.getTime(),status,repositories:[repository("hson-demo2",this.root),repository("hson-live",new URL("../../hson-live",`file://${this.root}/`).pathname)],selection:{profile:this.selection.profile,ids:[...this.selection.ids].map(x=>this.redactor.text(x,1024).value)},totals,diagnostics:this.diagnostics,artifacts:[],suites}}
 private minimal(reason:unknown):RunReport{this.add("reporter",reason);return this.report([],"error")}
 private async admit_artifacts(incomplete:string,suites:readonly SuiteReport[]):Promise<readonly SuiteReport[]>{let total=0,index=0;const copy=async(a:any)=>{try{if(typeof a.path!=="string"||a.path.includes("..")||a.path.startsWith("/"))throw new Error("LOCAL_ARTIFACT_UNSAFE_PATH");const source=resolve(this.root,a.path),state=await lstat(source);if(!source.startsWith(resolve(this.root)+"/")||state.isSymbolicLink()||!state.isFile()||state.size>8*1024*1024||total+state.size>128*1024*1024)throw new Error("LOCAL_ARTIFACT_REJECTED");const path=`artifacts/${String(++index).padStart(4,"0")}-${basename(a.path).replace(/[^A-Za-z0-9._-]/g,"_")}`;await mkdir(join(incomplete,"artifacts"),{recursive:true});await copyFile(source,join(incomplete,path));total+=state.size;return {...a,path,bytes:state.size}}catch(error){this.add("artifact",error);return undefined}};return Promise.all(suites.map(async s=>({...s,artifacts:(await Promise.all(s.artifacts.map(copy))).filter(Boolean) as any,cases:await Promise.all(s.cases.map(async c=>({...c,artifacts:(await Promise.all(c.artifacts.map(copy))).filter(Boolean) as any})))})))}
 async finalize(options:Readonly<{injectMaterializerFailure?:boolean;injectCatastrophicMaterializerFailure?:boolean;injectNormalizationFailure?:boolean}>={}):Promise<RunReport>{const incomplete=await begin_run(this.root,this.id);let report:RunReport;try{if(options.injectNormalizationFailure)throw new Error("INJECTED_NORMALIZATION_FAILURE");report=this.report(this.adapter.finalize());if(Buffer.byteLength(JSON.stringify(report))>32*1024*1024)throw new Error("RUN_REPORT_TOO_LARGE")}catch(error){report=this.minimal(error)}
  if(report.suites.length) report={...report,suites:await this.admit_artifacts(incomplete,report.suites)};
  let site=false;try{if(options.injectMaterializerFailure||options.injectCatastrophicMaterializerFailure)throw new Error(options.injectCatastrophicMaterializerFailure?"INJECTED_CATASTROPHIC_MATERIALIZER_FAILURE":"INJECTED_MATERIALIZER_FAILURE");await materialize_run_site(incomplete,report,this.redactor);site=true}catch(error){report=this.minimal(error);try{if(options.injectCatastrophicMaterializerFailure)throw error;await materialize_run_site(incomplete,report,this.redactor);site=true}catch{site=false}}
  await finalize_run(this.root,report,incomplete,site);return report}
}
