import { lstat, readdir, readFile } from "node:fs/promises";
import { join, resolve } from "node:path";
const safe=(p:unknown):p is string=>typeof p==="string"&&p.length>0&&!p.startsWith("/")&&!p.includes("\\")&&!p.split("/").some(x=>x===""||x==="."||x==="..");
const statuses=new Set(["pass","fail","skip","unsupported","cancelled","error"]), forbidden=/\bBearer\s+(?!<redacted>)[A-Za-z0-9._~+\/-]+=*|\b(token|secret|password|credential)\s*[=:]\s*(?!<redacted>)|\/(?:Users|home)\/[A-Za-z0-9_.-]+/i;
export async function validate_run_site(runDir:string):Promise<void>{
 const site=join(runDir,"site"),root=resolve(site),seen=new Set<string>(),ids=new Set<string>();
 const load=async(file:string)=>{if(!safe(file)||seen.has(file))throw new Error(`SITE_REFERENCE_INVALID:${file}`);const path=resolve(site,file);if(!path.startsWith(root+"/"))throw new Error("SITE_PATH_ESCAPE");const state=await lstat(path);if(state.isSymbolicLink()||!state.isFile()||state.size>32*1024*1024)throw new Error("SITE_UNSAFE_FILE");seen.add(file);const raw=await readFile(path,"utf8");if(forbidden.test(raw))throw new Error("PUBLIC_REDACTION_SURVIVED");const value:unknown=JSON.parse(raw);if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("SITE_JSON_SHAPE");return value as Record<string,unknown>;};
 const artifact=async(value:unknown)=>{const a=value as {path?:unknown};if(!a||!safe(a.path)||!a.path.startsWith("artifacts/")||seen.has(a.path))throw new Error("SITE_ARTIFACT_PATH");const full=resolve(site,a.path),state=await lstat(full);if(!full.startsWith(root+"/")||state.isSymbolicLink()||!state.isFile())throw new Error("SITE_ARTIFACT_PATH");seen.add(a.path);};
 const index=await load("index.json");if(typeof index.runId!=="string"||!statuses.has(String(index.status))||!Array.isArray(index.categories)||!Array.isArray(index.suites)||!Array.isArray(index.repositories)||!Array.isArray(index.diagnostics)||!Array.isArray(index.artifacts)||!index.totals||typeof index.totals!=="object")throw new Error("SITE_INDEX_SHAPE");for(const a of index.artifacts)await artifact(a);
 const suiteRefs=new Map<string,string>();for(const ref of index.suites as any[]){if(!ref||typeof ref.id!=="string"||!safe(ref.file)||ids.has(`suite:${ref.id}`))throw new Error("SITE_SUITE_REF");ids.add(`suite:${ref.id}`);suiteRefs.set(ref.id,ref.file);}
 for(const ref of index.categories as any[]){if(!ref||typeof ref.id!=="string"||!safe(ref.file)||!statuses.has(ref.status)||!ref.totals||ids.has(`cat:${ref.id}`))throw new Error("SITE_CATEGORY_REF");ids.add(`cat:${ref.id}`);const category=await load(ref.file);if(category.id!==ref.id||!Array.isArray(category.suites))throw new Error("SITE_CATEGORY_SHAPE");for(const summary of category.suites as any[]){if(!summary||typeof summary.id!=="string"||summary.category!==ref.id||!statuses.has(summary.status)||!safe(summary.file)||suiteRefs.get(summary.id)!==summary.file)throw new Error("SITE_CATEGORY_SUITE_REF");}}
 for(const [suiteId,suiteFile] of suiteRefs){const suite=await load(suiteFile);if(suite.id!==suiteId||!Array.isArray(suite.cases)||!Array.isArray(suite.diagnostics)||!Array.isArray(suite.artifacts)||!statuses.has(String(suite.status)))throw new Error("SITE_SUITE_SHAPE");for(const a of suite.artifacts)await artifact(a);const caseIds=new Set<string>();for(const ref of suite.cases as any[]){if(!ref||typeof ref.id!=="string"||caseIds.has(ref.id)||!statuses.has(ref.status)||!safe(ref.file))throw new Error("SITE_CASE_REF");caseIds.add(ref.id);const value=await load(ref.file);if(value.id!==ref.id||!statuses.has(String(value.status))||!Array.isArray(value.diagnostics)||!Array.isArray(value.artifacts))throw new Error("SITE_CASE_SHAPE");for(const a of value.artifacts)await artifact(a);}}
 for(const folder of ["categories","suites","cases","artifacts"])for(const entry of await readdir(join(site,folder)))if(!seen.has(`${folder}/${entry}`))throw new Error(`SITE_UNREFERENCED_FILE:${folder}/${entry}`);
}
