import type { TestEvent } from "../../core/test-contracts";
import { reduce_status, totals_for, type ArtifactReference, type CaseReport, type Diagnostic, type SubprocessEvidence, type SuiteReport, type TerminalStatus } from "./run-report-contract";
import type { LocalRedactor } from "./run-report-redaction";
type MutableCase = Omit<CaseReport, "status" | "endedAt" | "durationMs" | "diagnostics" | "artifacts"> & { status?: TerminalStatus; endedAt?: string; durationMs?: number; diagnostics: Diagnostic[]; artifacts: ArtifactReference[] };
type MutableSuite = { id: string; title: string; category: string; startedAt: string; endedAt?: string; diagnostics: Diagnostic[]; artifacts: ArtifactReference[]; cases: Map<string, MutableCase>; subprocess?: SubprocessEvidence; status?: TerminalStatus };
export class TestEventAdapter {
  readonly #suites = new Map<string, MutableSuite>();
  constructor(private readonly redactor: LocalRedactor, private readonly now: () => Date = () => new Date()) {}
  #suite(id: string, title?: string, category?: string): MutableSuite { const prior = this.#suites.get(id); if (prior) { if (title !== undefined && prior.title === id) prior.title = title; if (category !== undefined && prior.category === (id.split("/")[0] ?? "")) prior.category = category; return prior; } const suite = { id, title: title ?? id, category: category ?? id.split("/")[0] ?? "", startedAt: this.now().toISOString(), diagnostics: [], artifacts: [], cases: new Map<string, MutableCase>() }; this.#suites.set(id, suite); return suite; }
  ingest(event: TestEvent): void {
    const at = this.now().toISOString();
    if (event.t === "suite_begin") { this.#suite(event.suite, event.title, event.category); return; }
    if (event.t === "external_state") { this.#suite(event.suite, event.name, event.category ?? event.subject); return; }
    if (event.t === "external_end") { const suite = this.#suite(event.suite, event.name, event.category ?? event.subject); const protocolError = event.protocolError !== undefined; const unexpectedExit = event.status !== "cancelled" && event.terminalStatus !== "fail" && event.exitCode !== 0; const processError = event.timedOut || event.spawnError !== undefined || event.signal !== null || unexpectedExit; suite.status = event.status === "cancelled" && event.terminalAcceptedBeforeCancellation !== true ? "cancelled" : protocolError || processError ? "error" : event.terminalStatus ?? event.status; suite.endedAt = at; suite.subprocess = { exitCode: event.exitCode, signal: event.signal, timedOut: event.timedOut, cancelled: event.cancelled === true || event.status === "cancelled", forceKilled: event.forceKilled === true, stdout: this.redactor.text(event.stdout, 256 * 1024).value, stderr: this.redactor.text(event.stderr, 256 * 1024).value, stdoutBytes: event.stdoutBytes ?? Buffer.byteLength(event.stdout), stderrBytes: event.stderrBytes ?? Buffer.byteLength(event.stderr), stdoutTruncated: event.stdoutTruncated === true, stderrTruncated: event.stderrTruncated === true }; if (protocolError) suite.diagnostics.push(this.redactor.diagnostic("external-protocol", event.protocolError!)); if (event.spawnError) suite.diagnostics.push(this.redactor.diagnostic("spawn", event.spawnError)); return; }
    const suite = this.#suite(event.suite); if (event.t === "case_begin") { suite.cases.set(event.caseId, { id: event.caseId, title: event.name, startedAt: at, diagnostics: [], artifacts: [] }); return; }
    if (event.t === "case_end" || event.t === "case_cancelled") { const prior = suite.cases.get(event.caseId) ?? { id: event.caseId, title: event.name, startedAt: at, diagnostics: [], artifacts: [] }; if (prior.status !== undefined) return; const failure = event.t === "case_end" && event.err ? [this.redactor.diagnostic("test", event.err)] : []; suite.cases.set(event.caseId, { ...prior, status: event.t === "case_cancelled" ? "cancelled" : event.status, endedAt: at, durationMs: event.ms, diagnostics: [...prior.diagnostics, ...failure] }); return; }
    if (event.t === "evidence") { const target = event.caseId === undefined ? undefined : suite.cases.get(event.caseId); const diagnostic = this.redactor.diagnostic(event.kind, event.content); if (event.kind === "artifact" && event.reference && event.mediaType) (target?.artifacts ?? suite.artifacts).push({ name: this.redactor.text(event.name, 1024).value, mediaType: event.mediaType, path: event.reference, bytes: event.knownBytes ?? 0, truncated: event.truncated === true }); else (target?.diagnostics ?? suite.diagnostics).push(diagnostic); return; }
    if (event.t === "suite_end") suite.endedAt = at;
  }
  finalize(): readonly SuiteReport[] { return [...this.#suites.values()].map((suite) => { const cases = [...suite.cases.values()].filter((c): c is MutableCase & { status: TerminalStatus; endedAt: string; durationMs: number } => c.status !== undefined && c.endedAt !== undefined && c.durationMs !== undefined).map((c) => ({ ...c, status: c.status, endedAt: c.endedAt, durationMs: c.durationMs })); const status = suite.status ?? reduce_status(cases.map((c) => c.status)); return { id: suite.id, title: suite.title, category: suite.category, status, startedAt: suite.startedAt, endedAt: suite.endedAt ?? new Date().toISOString(), durationMs: Math.max(0, Date.parse(suite.endedAt ?? suite.startedAt) - Date.parse(suite.startedAt)), totals: totals_for(cases), diagnostics: suite.diagnostics, artifacts: suite.artifacts, cases, ...(suite.subprocess ? { subprocess: suite.subprocess } : {}) }; }); }
}
