/* Generated by Hson Schema hson-schema-mvp-7. Do not edit. */
import type { HsonNumber, HsonSchemaMutationCandidate } from "hson-live";
import type { HsonCanonical } from "hson-live/hson";
abstract class __OKLCH_SCHEMARootM1ItemM1M0MinR0Proof0 { declare private readonly __hsonSchemaProof0: void; }
abstract class __OKLCH_SCHEMARootM1ItemM1M0MaxR1Proof1 { declare private readonly __hsonSchemaProof1: void; }
abstract class __OKLCH_SCHEMARootM1ItemM1M1MinR0Proof2 { declare private readonly __hsonSchemaProof2: void; }
abstract class __OKLCH_SCHEMARootM1ItemM1M1MaxR1Proof3 { declare private readonly __hsonSchemaProof3: void; }
abstract class __OKLCH_SCHEMARootM1ItemM1M2MinR0Proof4 { declare private readonly __hsonSchemaProof4: void; }
abstract class __OKLCH_SCHEMARootM1ItemM1M2MaxR1Proof5 { declare private readonly __hsonSchemaProof5: void; }
abstract class __OKLCH_SCHEMARootM1ItemM1M3MinR0Proof6 { declare private readonly __hsonSchemaProof6: void; }
abstract class __OKLCH_SCHEMARootM1ItemM1M3MaxR1Proof7 { declare private readonly __hsonSchemaProof7: void; }
abstract class __OKLCH_SCHEMARootM1ItemM1ObjectProof8 { declare private readonly __hsonSchemaProof8: void; }
abstract class __OKLCH_SCHEMARootM1ItemObjectProof9 { declare private readonly __hsonSchemaProof9: void; }
abstract class __OKLCH_SCHEMARootM1ArrayProof10 { declare private readonly __hsonSchemaProof10: void; }
abstract class __OKLCH_SCHEMARootObjectProof11 { declare private readonly __hsonSchemaProof11: void; }
abstract class __OKLCH_SCHEMAHsonProof12 { declare private readonly __hsonSchemaProof12: void; }
export type OKLCH_SCHEMAType = Readonly<{ readonly activePath: string; readonly tokens: ReadonlyArray<Readonly<{ readonly path: string; readonly value: Readonly<{ readonly l: HsonNumber & HsonSchemaMutationCandidate<number> & __OKLCH_SCHEMARootM1ItemM1M0MinR0Proof0 & HsonSchemaMutationCandidate<number> & __OKLCH_SCHEMARootM1ItemM1M0MaxR1Proof1 & HsonSchemaMutationCandidate<number>; readonly c: HsonNumber & HsonSchemaMutationCandidate<number> & __OKLCH_SCHEMARootM1ItemM1M1MinR0Proof2 & HsonSchemaMutationCandidate<number> & __OKLCH_SCHEMARootM1ItemM1M1MaxR1Proof3 & HsonSchemaMutationCandidate<number>; readonly h: HsonNumber & HsonSchemaMutationCandidate<number> & __OKLCH_SCHEMARootM1ItemM1M2MinR0Proof4 & HsonSchemaMutationCandidate<number> & __OKLCH_SCHEMARootM1ItemM1M2MaxR1Proof5 & HsonSchemaMutationCandidate<number>; readonly a: HsonNumber & HsonSchemaMutationCandidate<number> & __OKLCH_SCHEMARootM1ItemM1M3MinR0Proof6 & HsonSchemaMutationCandidate<number> & __OKLCH_SCHEMARootM1ItemM1M3MaxR1Proof7 & HsonSchemaMutationCandidate<number>; }> & __OKLCH_SCHEMARootM1ItemM1ObjectProof8 & HsonSchemaMutationCandidate<{ l: number; c: number; h: number; a: number; }>; }> & __OKLCH_SCHEMARootM1ItemObjectProof9 & HsonSchemaMutationCandidate<{ path: string; value: { l: number; c: number; h: number; a: number; }; }>> & __OKLCH_SCHEMARootM1ArrayProof10 & HsonSchemaMutationCandidate<Array<{ path: string; value: { l: number; c: number; h: number; a: number; }; }>>; }> & __OKLCH_SCHEMARootObjectProof11 & HsonSchemaMutationCandidate<{ activePath: string; tokens: Array<{ path: string; value: { l: number; c: number; h: number; a: number; }; }>; }>;
export type OKLCH_SCHEMAHson = HsonCanonical & __OKLCH_SCHEMAHsonProof12;
