/* Generated by Hson Schema hson-schema-mvp-6. Do not edit. */
import type { HsonNumber } from "hson-live";
import type { HsonCanonical } from "hson-live/hson";
abstract class __OKLCH_SCHEMARootM1ItemM1M0MinR0Proof0 { declare private readonly __hsonSchemaProof0: void; }
abstract class __OKLCH_SCHEMARootM1ItemM1M0MaxR1Proof1 { declare private readonly __hsonSchemaProof1: void; }
abstract class __OKLCH_SCHEMARootM1ItemM1M1MinR0Proof2 { declare private readonly __hsonSchemaProof2: void; }
abstract class __OKLCH_SCHEMARootM1ItemM1M1MaxR1Proof3 { declare private readonly __hsonSchemaProof3: void; }
abstract class __OKLCH_SCHEMARootM1ItemM1M2MinR0Proof4 { declare private readonly __hsonSchemaProof4: void; }
abstract class __OKLCH_SCHEMARootM1ItemM1M2MaxR1Proof5 { declare private readonly __hsonSchemaProof5: void; }
abstract class __OKLCH_SCHEMARootM1ItemM1M3MinR0Proof6 { declare private readonly __hsonSchemaProof6: void; }
abstract class __OKLCH_SCHEMARootM1ItemM1M3MaxR1Proof7 { declare private readonly __hsonSchemaProof7: void; }
abstract class __OKLCH_SCHEMARootM1ItemM1ObjectProof8 { declare private readonly __hsonSchemaProof8: void; }
abstract class __OKLCH_SCHEMARootM1ItemObjectProof9 { declare private readonly __hsonSchemaProof9: void; }
abstract class __OKLCH_SCHEMARootM1ArrayProof10 { declare private readonly __hsonSchemaProof10: void; }
abstract class __OKLCH_SCHEMARootObjectProof11 { declare private readonly __hsonSchemaProof11: void; }
abstract class __OKLCH_SCHEMAHsonProof12 { declare private readonly __hsonSchemaProof12: void; }
export type OKLCH_SCHEMAType = Readonly<{ readonly activePath: string; readonly tokens: ReadonlyArray<Readonly<{ readonly path: string; readonly value: Readonly<{ readonly l: HsonNumber & __OKLCH_SCHEMARootM1ItemM1M0MinR0Proof0 & __OKLCH_SCHEMARootM1ItemM1M0MaxR1Proof1; readonly c: HsonNumber & __OKLCH_SCHEMARootM1ItemM1M1MinR0Proof2 & __OKLCH_SCHEMARootM1ItemM1M1MaxR1Proof3; readonly h: HsonNumber & __OKLCH_SCHEMARootM1ItemM1M2MinR0Proof4 & __OKLCH_SCHEMARootM1ItemM1M2MaxR1Proof5; readonly a: HsonNumber & __OKLCH_SCHEMARootM1ItemM1M3MinR0Proof6 & __OKLCH_SCHEMARootM1ItemM1M3MaxR1Proof7; }> & __OKLCH_SCHEMARootM1ItemM1ObjectProof8; }> & __OKLCH_SCHEMARootM1ItemObjectProof9> & __OKLCH_SCHEMARootM1ArrayProof10; }> & __OKLCH_SCHEMARootObjectProof11;
export type OKLCH_SCHEMAHson = HsonCanonical & __OKLCH_SCHEMAHsonProof12;
