export const GENERATED_JSON_SEED_ENVIRONMENT = "HOSTED_FUZZ_SEED";
export const GENERATED_JSON_COUNT_ENVIRONMENT = "HOSTED_FUZZ_CASES";
export const DEFAULT_GENERATED_JSON_SEED = 1;
export const DEFAULT_GENERATED_JSON_CASES = 200;
