/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false src/hosted-test/cloudflare/worker-configuration.d.ts` (hash: 0f7efd81fa4bc1ba345594f0757e6df5)
interface __BaseEnv_Env {
	HOSTED_TESTS: DurableObjectNamespace<import("./worker").HostedTestDurableObject>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "HostedTestDurableObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
