import type { LiveTree } from "hson-live/livetree";
import { OKLCH_VIBRANT } from "../../../core/consts/oklch.consts";
import type { FrozenDiagnostic, FrozenPublicAttachment, FrozenRowArtifact, FrozenTestEvidenceIndex, FrozenTestSuite, FrozenTestTiming } from "./frozen-test-evidence-client";

export function format_frozen_evidence_size(rawBytes: number): string { if (rawBytes < 1_000) return `${rawBytes} B`; if (rawBytes < 1_000_000) return `${(rawBytes / 1_000).toFixed(1)} kB`; return `${(rawBytes / 1_000_000).toFixed(1)} MB`; }
export function format_frozen_test_duration(timing: FrozenTestTiming): string { const value = timing.durationMs; if (value < 1) return `${value.toFixed(2)} ms`; if (value < 1_000) return `${value.toFixed(1)} ms`; return `${(value / 1_000).toFixed(2)} s`; }
function diagnostic_text(diagnostic: FrozenDiagnostic): string { return [`[${diagnostic.kind}]${diagnostic.truncated ? " (truncated)" : ""}`, diagnostic.message, diagnostic.expected === undefined ? "" : `expected: ${diagnostic.expected}`, diagnostic.actual === undefined ? "" : `actual: ${diagnostic.actual}`, diagnostic.stack ?? ""].filter(Boolean).join("\n"); }
function attachment_text(attachment: FrozenPublicAttachment): string { return `[attachment] ${attachment.name} · ${attachment.mediaType} · ${format_frozen_evidence_size(attachment.bytes)}${attachment.truncated ? " · truncated" : ""}\n${attachment.path}`; }
export function serialize_frozen_row_artifact(artifact: FrozenRowArtifact): string { const id=artifact.owner==="case"?artifact.caseId:artifact.suiteId; const lines=[artifact.title,`id: ${id}`,`${artifact.status.toUpperCase()}${artifact.owner==="suite"?` · ${artifact.category}`:""}`,`duration: ${format_frozen_test_duration(artifact)}`]; for(const diagnostic of artifact.diagnostics)lines.push("",diagnostic_text(diagnostic)); for(const attachment of artifact.artifacts)lines.push("",attachment_text(attachment)); if(artifact.owner==="suite"&&artifact.subprocess!==undefined)lines.push("","[subprocess]",JSON.stringify(artifact.subprocess,null,2)); return lines.join("\n"); }
export function serialize_frozen_index_summary(index: FrozenTestEvidenceIndex): string { const lines=["Test reports",`run: ${index.runId}`,`status: ${index.status.toUpperCase()}`,`started: ${index.startedAt}`,`duration: ${format_frozen_test_duration(index)}`,`totals: ${index.overall.suites} suites · ${index.overall.cases} cases · ${index.overall.pass} pass · ${index.overall.fail} fail · ${index.overall.skip} skip · ${index.overall.unsupported} unsupported · ${index.overall.cancelled} cancelled · ${index.overall.error} error`]; for(const repository of index.repositories)lines.push(`repository: ${repository.name} · ${repository.revision?.slice(0,12)??"revision unavailable"}${repository.dirty===null?"":repository.dirty?" · dirty":" · clean"}`); for(const diagnostic of index.diagnostics)lines.push("",diagnostic_text(diagnostic)); for(const category of index.categories)lines.push("",`${category.id} · ${category.status.toUpperCase()} · ${category.counts.suites} suites · ${category.counts.cases} cases`); return lines.join("\n"); }
export type FrozenEvidenceSurface = Readonly<{ root: LiveTree; dispose(): void }>;
export function mount_frozen_generic_evidence(host:LiveTree,artifact:FrozenRowArtifact,options:Readonly<{onClose?:()=>void;reportRoot?:string}>={}):FrozenEvidenceSurface { const id=artifact.owner==="case"?artifact.caseId:artifact.suiteId; const root=host.create.div().attrs.setMany({role:"region","aria-label":`Evidence for ${id}`,"data-testid":"frozen-row-evidence","data-frozen-evidence-owner":artifact.owner}).css.setMany({position:"absolute",inset:"0",zIndex:"120",display:"grid",gridTemplateRows:"auto minmax(0,1fr)",padding:"1rem",boxSizing:"border-box",background:OKLCH_VIBRANT.voidInk,color:OKLCH_VIBRANT.ghost,fontFamily:'"DM Mono",ui-monospace,monospace',pointerEvents:"auto"}); const header=root.create.header().css.setMany({display:"grid",gridTemplateColumns:"minmax(0,1fr) auto",gap:"1rem",borderBottom:`1px solid ${OKLCH_VIBRANT.graphite}`,paddingBottom:".75rem"}); const identity=header.create.div(); identity.create.div().attrs.set("data-testid","frozen-inspector-navigation").text.set(`Saved ${artifact.owner} report · Browser Back returns to the tests explorer`).css.setMany({color:OKLCH_VIBRANT.cyanGlass,marginBottom:".35rem"}); identity.create.div().text.set(id).css.setMany({color:OKLCH_VIBRANT.cyanGlass,overflowWrap:"anywhere"}); const close=header.create.button().attrs.setMany({type:"button","aria-label":`Close ${artifact.owner} report`}).text.set("[ close ]").css.setMany({color:OKLCH_VIBRANT.cyanGlass,background:OKLCH_VIBRANT.voidInk,border:`1px solid ${OKLCH_VIBRANT.graphite}`,padding:".35rem .6rem",cursor:"pointer"}); const body=root.create.div().attrs.set("data-frozen-report-scroll","true").css.setMany({overflow:"auto",minHeight:"0",paddingTop:"1rem"}); body.create.pre().attrs.setMany({"data-testid":"frozen-row-evidence-text"}).text.set(serialize_frozen_row_artifact(artifact)).css.setMany({whiteSpace:"pre-wrap",margin:"0"}); if(options.reportRoot!==undefined&&artifact.artifacts.length>0){const attachments=body.create.div().attrs.set("data-testid","frozen-public-attachments"); for(const item of artifact.artifacts){const href=`${options.reportRoot}/${item.path}`; if(item.mediaType.startsWith("image/"))attachments.create.img().attrs.setMany({src:href,alt:item.name,loading:"lazy"}).css.setMany({display:"block",maxWidth:"100%",marginTop:"1rem"}); else attachments.create.a().attrs.setMany({href,target:"_blank",rel:"noopener"}).text.set(`${item.name} (${item.mediaType})`).css.setMany({display:"block",color:OKLCH_VIBRANT.cyanGlass,marginTop:".75rem"}); }} let disposed=false; const dispose=()=>{if(disposed)return;disposed=true;listener.off();if(!root.isDisposed)root.remove();}; const listener=close.listen.onClick(()=>options.onClose?.()??dispose()); return Object.freeze({root,dispose}); }
export function frozen_suite_row_timing(suite: FrozenTestSuite): string { return format_frozen_test_duration(suite); }
