export const DIRECT_TEST_STATUSES = Object.freeze(["pass", "fail", "skip", "unsupported", "cancelled", "error"] as const);
export type FrozenTestStatus = typeof DIRECT_TEST_STATUSES[number];
export type FrozenTestExplorerCategoryId = string;
export type FrozenTestExplorerTotals = Readonly<Record<FrozenTestStatus, number> & { cases: number; suites: number }>;
export type FrozenTestTiming = Readonly<{ startedAt: string; endedAt: string; durationMs: number }>;
export type FrozenEvidenceReference = Readonly<{ id: string; file: string }>;
export type FrozenDiagnostic = Readonly<{ kind: string; message: string; stack?: string; expected?: string; actual?: string; truncated: boolean }>;
export type FrozenPublicAttachment = Readonly<{ name: string; mediaType: "text/plain" | "application/json" | "image/png" | "image/jpeg" | "image/webp"; path: string; bytes: number; truncated: boolean }>;
export type FrozenRepository = Readonly<{ name: string; revision: string | null; dirty: boolean | null }>;
export type FrozenTestCategory = Readonly<{ id: string; status: FrozenTestStatus; counts: FrozenTestExplorerTotals; listing: FrozenEvidenceReference }>;
export type FrozenTestSuite = Readonly<FrozenTestTiming & { id: string; title: string; category: string; status: FrozenTestStatus; counts: FrozenTestExplorerTotals; listing: FrozenEvidenceReference }>;
export type FrozenTestCase = Readonly<FrozenTestTiming & { id: string; caseId: string; title: string; status: FrozenTestStatus; evidence: FrozenEvidenceReference }>;
export type FrozenTestEvidenceIndex = Readonly<FrozenTestTiming & { runId: string; status: FrozenTestStatus; repositories: readonly FrozenRepository[]; overall: FrozenTestExplorerTotals; diagnostics: readonly FrozenDiagnostic[]; artifacts: readonly FrozenPublicAttachment[]; categories: readonly FrozenTestCategory[] }>;
export type FrozenTestCategoryListing = Readonly<{ categoryId: string; suites: readonly FrozenTestSuite[] }>;
export type FrozenTestSuiteListing = Readonly<{ categoryId: string; suiteId: string; cases: readonly FrozenTestCase[]; detail: FrozenSuiteArtifact }>;
export type FrozenCaseArtifact = Readonly<FrozenTestTiming & { owner: "case"; suiteId: string; caseId: string; title: string; status: FrozenTestStatus; diagnostics: readonly FrozenDiagnostic[]; artifacts: readonly FrozenPublicAttachment[] }>;
export type FrozenSuiteArtifact = Readonly<FrozenTestTiming & { owner: "suite"; category: string; suiteId: string; title: string; status: FrozenTestStatus; counts: FrozenTestExplorerTotals; diagnostics: readonly FrozenDiagnostic[]; artifacts: readonly FrozenPublicAttachment[]; subprocess?: Readonly<Record<string, unknown>> }>;
export type FrozenRowArtifact = FrozenCaseArtifact | FrozenSuiteArtifact;
export type FrozenRowEvidenceSelection = Readonly<{ suite: FrozenTestSuite; testCase: FrozenTestCase; reference: FrozenEvidenceReference }>;

export class FrozenTestEvidenceError extends Error { constructor(readonly code: string, message: string, options?: ErrorOptions) { super(`${code}: ${message}`, options); this.name = "FrozenTestEvidenceError"; } }
type FetchLike = (input: string, init?: RequestInit) => Promise<Pick<Response, "ok" | "status" | "text">>;
export type FrozenTestEvidenceClient = Readonly<{ root: string; runId: string; loadIndex(): Promise<FrozenTestEvidenceIndex>; loadCategory(category: FrozenTestCategory): Promise<FrozenTestCategoryListing>; loadSuite(suite: FrozenTestSuite): Promise<FrozenTestSuiteListing>; loadRowEvidence(selection: FrozenRowEvidenceSelection): Promise<FrozenCaseArtifact>; releaseRowEvidence(path?: string): void; snapshot(): Readonly<{ indexRequests: number; categoryRequests: number; suiteRequests: number; rowEvidenceRequests: number; retainedRowArtifacts: number }> }>;

function fail(code: string, message: string): never { throw new FrozenTestEvidenceError(code, message); }
function object(value: unknown, at: string): Record<string, unknown> { if (typeof value !== "object" || value === null || Array.isArray(value)) fail("FROZEN_INDEX_MALFORMED", `${at} must be an object.`); return value as Record<string, unknown>; }
function list(value: unknown, at: string): unknown[] { if (!Array.isArray(value)) fail("FROZEN_INDEX_MALFORMED", `${at} must be an array.`); return value; }
function text(value: unknown, at: string): string { if (typeof value !== "string" || value.length === 0) fail("FROZEN_INDEX_MALFORMED", `${at} must be a non-empty string.`); return value; }
function number(value: unknown, at: string, integer = false): number { if (typeof value !== "number" || !Number.isFinite(value) || value < 0 || (integer && !Number.isInteger(value))) fail("FROZEN_INDEX_MALFORMED", `${at} must be a non-negative number.`); return value; }
function status(value: unknown, at: string): FrozenTestStatus { if (!DIRECT_TEST_STATUSES.includes(value as FrozenTestStatus)) fail("FROZEN_INDEX_MALFORMED", `${at} has an invalid terminal status.`); return value as FrozenTestStatus; }
function file(value: unknown, at: string, folder: "categories" | "suites" | "cases" | "artifacts"): string { const path = text(value, at); if (!path.startsWith(`${folder}/`) || path.startsWith("/") || path.includes("\\") || path.includes("%") || path.includes("?") || path.includes("#") || path.split("/").some(part => part === "" || part === "." || part === "..")) fail("FROZEN_INDEX_EVIDENCE_PATH", `${at} is not a safe ${folder} reference.`); return path; }
function reference(value: unknown, at: string, folder: "categories" | "suites" | "cases", expectedId?: string): FrozenEvidenceReference { const source = object(value, at), id = text(source.id, `${at}.id`); if (expectedId !== undefined && id !== expectedId) fail("FROZEN_INDEX_RELATIONSHIP", `${at} does not identify ${expectedId}.`); return Object.freeze({ id, file: file(source.file, `${at}.file`, folder) }); }
function timing(source: Record<string, unknown>, at: string): FrozenTestTiming { const startedAt = text(source.startedAt, `${at}.startedAt`), endedAt = text(source.endedAt, `${at}.endedAt`); if (!Number.isFinite(Date.parse(startedAt)) || !Number.isFinite(Date.parse(endedAt))) fail("FROZEN_INDEX_MALFORMED", `${at} timestamps must be ISO dates.`); return Object.freeze({ startedAt, endedAt, durationMs: number(source.durationMs, `${at}.durationMs`) }); }
function totals(value: unknown, at: string): FrozenTestExplorerTotals { const source = object(value, at), result = Object.fromEntries([...DIRECT_TEST_STATUSES, "cases", "suites"].map(key => [key, number(source[key], `${at}.${key}`, true)])) as Record<string, number>; if (DIRECT_TEST_STATUSES.reduce((sum, key) => sum + result[key]!, 0) !== result.cases) fail("FROZEN_INDEX_RELATIONSHIP", `${at} terminal counts do not balance with cases.`); return Object.freeze(result) as FrozenTestExplorerTotals; }
function diagnostics(value: unknown, at: string): readonly FrozenDiagnostic[] { return Object.freeze(list(value, at).map((item, index) => { const source = object(item, `${at}[${index}]`); if (typeof source.truncated !== "boolean") fail("FROZEN_INDEX_MALFORMED", `${at}[${index}].truncated must be boolean.`); const result: Record<string, unknown> = { kind: text(source.kind, `${at}[${index}].kind`), message: text(source.message, `${at}[${index}].message`), truncated: source.truncated }; for (const key of ["stack", "expected", "actual"] as const) if (source[key] !== undefined) result[key] = text(source[key], `${at}[${index}].${key}`); return Object.freeze(result) as FrozenDiagnostic; })); }
function attachments(value: unknown, at: string): readonly FrozenPublicAttachment[] { const allowed = new Set(["text/plain", "application/json", "image/png", "image/jpeg", "image/webp"]); return Object.freeze(list(value, at).map((item, index) => { const source = object(item, `${at}[${index}]`), mediaType = text(source.mediaType, `${at}[${index}].mediaType`); if (!allowed.has(mediaType) || typeof source.truncated !== "boolean") fail("FROZEN_INDEX_MALFORMED", `${at}[${index}] is not a supported public attachment.`); return Object.freeze({ name: text(source.name, `${at}[${index}].name`), mediaType, path: file(source.path, `${at}[${index}].path`, "artifacts"), bytes: number(source.bytes, `${at}[${index}].bytes`, true), truncated: source.truncated }) as FrozenPublicAttachment; })); }
const totalKeys = [...DIRECT_TEST_STATUSES, "cases", "suites"] as const;
function sumTotals(items: readonly FrozenTestExplorerTotals[]): FrozenTestExplorerTotals { const sum = Object.fromEntries(totalKeys.map(key => [key, 0])) as Record<string, number>; for (const item of items) for (const key of totalKeys) sum[key] = (sum[key] ?? 0) + item[key]; return sum as FrozenTestExplorerTotals; }
function sameTotals(a: FrozenTestExplorerTotals, b: FrozenTestExplorerTotals): boolean { return totalKeys.every(key => a[key] === b[key]); }

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export function validate_frozen_test_evidence_root(configured: string | undefined): Readonly<{ root: string; runId: string }> { if (configured === undefined) fail("FROZEN_EVIDENCE_ROOT_MISSING", "No local report is available yet."); const root = configured.trim(); if (root === "") fail("FROZEN_EVIDENCE_ROOT_EMPTY", "No local report is available yet."); if (root.includes("?") || root.includes("#") || root.includes("\\") || root.split("/").some(segment => segment === "." || segment === "..")) fail("FROZEN_EVIDENCE_ROOT_INVALID", "Evidence root must be immutable, undecorated, and traversal-free."); const matched = /^\/test-evidence\/([^/]+)$/.exec(root); if (matched === null || !UUID.test(matched[1]!)) fail("FROZEN_EVIDENCE_ROOT_RUN_ID", "Evidence root must be /test-evidence/<UUID run-id>."); return Object.freeze({ root, runId: matched[1]! }); }

export function decode_frozen_test_evidence_index(value: unknown, expectedRunId: string): FrozenTestEvidenceIndex { const source = object(value, "index"), runId = text(source.runId, "index.runId"); if (runId !== expectedRunId) fail("FROZEN_INDEX_RUN_MISMATCH", "Index runId does not match its immutable root."); const categoryIds = new Set<string>(); const categories = Object.freeze(list(source.categories, "index.categories").map((item, index): FrozenTestCategory => { const at = `index.categories[${index}]`, entry = object(item, at), ref = reference(entry, at, "categories"), id = ref.id; if (categoryIds.has(id)) fail("FROZEN_INDEX_DUPLICATE_ID", `Duplicate category ${id}.`); categoryIds.add(id); return Object.freeze({ id, status: status(entry.status, `${at}.status`), counts: totals(entry.totals, `${at}.totals`), listing: ref }); })); const overall = totals(source.totals, "index.totals"); if (!sameTotals(sumTotals(categories.map(item => item.counts)), overall)) fail("FROZEN_INDEX_RELATIONSHIP", "Run totals do not match category totals."); const repositories = Object.freeze(list(source.repositories, "index.repositories").map((item, index): FrozenRepository => { const entry = object(item, `index.repositories[${index}]`); if ((entry.revision !== null && (typeof entry.revision !== "string" || !/^[0-9a-f]{40}$/i.test(entry.revision))) || (entry.dirty !== null && typeof entry.dirty !== "boolean")) fail("FROZEN_INDEX_MALFORMED", `index.repositories[${index}] metadata is invalid.`); return Object.freeze({ name: text(entry.name, `index.repositories[${index}].name`), revision: entry.revision as string | null, dirty: entry.dirty as boolean | null }); })); return Object.freeze({ runId, status: status(source.status, "index.status"), ...timing(source, "index"), repositories, overall, diagnostics: diagnostics(source.diagnostics, "index.diagnostics"), artifacts: attachments(source.artifacts, "index.artifacts"), categories }); }

export function decode_frozen_test_category_listing(value: unknown, category: FrozenTestCategory): FrozenTestCategoryListing { const source = object(value, "category"), id = text(source.id, "category.id"); if (id !== category.id) fail("FROZEN_INDEX_RELATIONSHIP", `Category artifact does not match ${category.id}.`); const ids = new Set<string>(); const suites = Object.freeze(list(source.suites, "category.suites").map((item, index): FrozenTestSuite => { const at = `category.suites[${index}]`, entry = object(item, at), ref = reference(entry, at, "suites"), suiteId = ref.id; if (ids.has(suiteId)) fail("FROZEN_INDEX_DUPLICATE_ID", `Duplicate suite ${suiteId}.`); if (text(entry.category, `${at}.category`) !== id) fail("FROZEN_INDEX_RELATIONSHIP", `Suite ${suiteId} belongs to another category.`); ids.add(suiteId); return Object.freeze({ id: suiteId, title: text(entry.title, `${at}.title`), category: id, status: status(entry.status, `${at}.status`), ...timing(entry, at), counts: totals(entry.totals, `${at}.totals`), listing: ref }); })); const observed={...sumTotals(suites.map(suite => suite.counts)),suites:suites.length}; if (!sameTotals(observed, category.counts)) fail("FROZEN_INDEX_RELATIONSHIP", `Category ${id} totals do not match its suites.`); return Object.freeze({ categoryId: id, suites }); }

export function decode_frozen_test_suite_listing(value: unknown, suite: FrozenTestSuite): FrozenTestSuiteListing { const source = object(value, "suite"); if (source.id !== suite.id || source.category !== suite.category || source.status !== suite.status) fail("FROZEN_INDEX_RELATIONSHIP", `Suite artifact does not match ${suite.id}.`); const ids = new Set<string>(); const cases = Object.freeze(list(source.cases, "suite.cases").map((item, index): FrozenTestCase => { const at = `suite.cases[${index}]`, entry = object(item, at), ref = reference(entry, at, "cases"), caseId = ref.id, id = `${suite.id}::${caseId}`; if (ids.has(id)) fail("FROZEN_INDEX_DUPLICATE_ID", `Duplicate case ${id}.`); ids.add(id); return Object.freeze({ id, caseId, title: text(entry.title, `${at}.title`), status: status(entry.status, `${at}.status`), ...timing(entry, at), evidence: ref }); })); const caseTotals = sumTotals(cases.map(item => Object.freeze({ pass:item.status==="pass"?1:0, fail:item.status==="fail"?1:0, skip:item.status==="skip"?1:0, unsupported:item.status==="unsupported"?1:0, cancelled:item.status==="cancelled"?1:0, error:item.status==="error"?1:0, cases:1, suites:0 }))); if (!sameTotals(caseTotals, Object.freeze({ ...suite.counts, suites: 0 }))) fail("FROZEN_INDEX_RELATIONSHIP", `Suite ${suite.id} totals do not match its cases.`); const detail: FrozenSuiteArtifact = Object.freeze({ owner:"suite", category:suite.category, suiteId:suite.id, title:suite.title, status:suite.status, ...timing(source,"suite"), counts:totals(source.totals,"suite.totals"), diagnostics:diagnostics(source.diagnostics,"suite.diagnostics"), artifacts:attachments(source.artifacts,"suite.artifacts"), ...(source.subprocess===undefined?{}:{subprocess:Object.freeze({...object(source.subprocess,"suite.subprocess")})}) }); return Object.freeze({ categoryId:suite.category, suiteId:suite.id, cases, detail }); }

export function validate_frozen_row_artifact(value: unknown, selection: FrozenRowEvidenceSelection): FrozenCaseArtifact { const source=object(value,"case"); if(source.id!==selection.testCase.caseId||source.status!==selection.testCase.status)fail("FROZEN_ROW_EVIDENCE_ID_MISMATCH",`Case artifact does not match ${selection.testCase.id}.`); return Object.freeze({owner:"case",suiteId:selection.suite.id,caseId:selection.testCase.id,title:selection.testCase.title,status:selection.testCase.status,...timing(source,"case"),diagnostics:diagnostics(source.diagnostics,"case.diagnostics"),artifacts:attachments(source.artifacts,"case.artifacts")}); }
export function project_frozen_test_explorer(index: FrozenTestEvidenceIndex) { return Object.freeze({ categories:Object.freeze(Object.fromEntries(index.categories.map(category=>[category.id,category.counts]))), overall:index.overall }); }

export function make_frozen_test_evidence_client(options: Readonly<{ root?: string; fetch?: FetchLike }> = {}): FrozenTestEvidenceClient { const configured=validate_frozen_test_evidence_root(options.root), fetcher=options.fetch??globalThis.fetch.bind(globalThis); let cached:FrozenTestEvidenceIndex|undefined,pending:Promise<FrozenTestEvidenceIndex>|undefined,currentRowArtifact:{path:string;request:Promise<{value:unknown}>}|undefined; let indexRequests=0,categoryRequests=0,suiteRequests=0,rowEvidenceRequests=0; const fetchJson=async(path:string,kind:"index"|"category"|"suite"|"row")=>{if(kind==="index")indexRequests++;else if(kind==="category")categoryRequests++;else if(kind==="suite")suiteRequests++;else rowEvidenceRequests++;let response;try{response=await fetcher(`${configured.root}/${path}`,{method:"GET",credentials:"same-origin"});}catch(cause){throw new FrozenTestEvidenceError("FROZEN_EVIDENCE_FETCH_FAILED",`Unable to load ${kind} evidence.`,{cause});}if(!response.ok)fail("FROZEN_EVIDENCE_HTTP",`${kind} evidence request failed with HTTP ${response.status}.`);try{return {value:JSON.parse(await response.text()) as unknown};}catch(cause){throw new FrozenTestEvidenceError("FROZEN_EVIDENCE_JSON",`${kind} evidence is not valid JSON.`,{cause});}}; return Object.freeze({root:configured.root,runId:configured.runId,loadIndex(){if(cached)return Promise.resolve(cached);pending??=fetchJson("index.json","index").then(({value})=>cached=decode_frozen_test_evidence_index(value,configured.runId)).finally(()=>{pending=undefined;});return pending;},async loadCategory(category){return decode_frozen_test_category_listing((await fetchJson(category.listing.file,"category")).value,category);},async loadSuite(suite){return decode_frozen_test_suite_listing((await fetchJson(suite.listing.file,"suite")).value,suite);},async loadRowEvidence(selection){const path=file(selection.reference.file,"case evidence path","cases");let request=currentRowArtifact?.path===path?currentRowArtifact.request:undefined;if(!request){request=fetchJson(path,"row");const owned={path,request};currentRowArtifact=owned;request.catch(()=>{if(currentRowArtifact===owned)currentRowArtifact=undefined;});}return validate_frozen_row_artifact((await request).value,selection);},releaseRowEvidence(path){if(path===undefined||currentRowArtifact?.path===path)currentRowArtifact=undefined;},snapshot:()=>Object.freeze({indexRequests,categoryRequests,suiteRequests,rowEvidenceRequests,retainedRowArtifacts:currentRowArtifact?1:0})}); }
