/* Generated by Hson Schema hson-schema-mvp-6. Do not edit. */
import type { HsonCanonical } from "hson-live/hson";
abstract class __CELLSHEET_WORKBOOK_SCHEMAD0TupleProof0 { declare private readonly __hsonSchemaProof0: void; }
abstract class __CELLSHEET_WORKBOOK_SCHEMAD0DefinitionProof1 { declare private readonly __hsonSchemaProof1: void; }
abstract class __CELLSHEET_WORKBOOK_SCHEMARootM0TupleProof2 { declare private readonly __hsonSchemaProof2: void; }
abstract class __CELLSHEET_WORKBOOK_SCHEMARootObjectProof3 { declare private readonly __hsonSchemaProof3: void; }
abstract class __CELLSHEET_WORKBOOK_SCHEMAHsonProof4 { declare private readonly __hsonSchemaProof4: void; }
type __CELLSHEET_WORKBOOK_SCHEMADefinition0 = (readonly [string, string, string, string, string, string, string, string] & __CELLSHEET_WORKBOOK_SCHEMAD0TupleProof0) & __CELLSHEET_WORKBOOK_SCHEMAD0DefinitionProof1;
export type CELLSHEET_WORKBOOK_SCHEMAType = Readonly<{ readonly cells: readonly [__CELLSHEET_WORKBOOK_SCHEMADefinition0, __CELLSHEET_WORKBOOK_SCHEMADefinition0, __CELLSHEET_WORKBOOK_SCHEMADefinition0, __CELLSHEET_WORKBOOK_SCHEMADefinition0, __CELLSHEET_WORKBOOK_SCHEMADefinition0, __CELLSHEET_WORKBOOK_SCHEMADefinition0, __CELLSHEET_WORKBOOK_SCHEMADefinition0, __CELLSHEET_WORKBOOK_SCHEMADefinition0] & __CELLSHEET_WORKBOOK_SCHEMARootM0TupleProof2; }> & __CELLSHEET_WORKBOOK_SCHEMARootObjectProof3;
export type CELLSHEET_WORKBOOK_SCHEMAHson = HsonCanonical & __CELLSHEET_WORKBOOK_SCHEMAHsonProof4;
