import { execFileSync } from "node:child_process";
import { copyFileSync, cpSync, existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const PACK_STAGES = Object.freeze([
  "verify-source",
  "build-runtime",
  "verify-package-surfaces",
  "capture-normal-evidence",
  "materialize",
  "assemble-and-verify-explorer",
]);

export const CERTIFICATION_RECEIPT = "certification-receipt.json";
export const CERTIFICATION_AUTHORITY = "npm run capture:deployment-tests:certification";

function is_deployment_root(path) {
  if (!existsSync(join(path, "package.json")) || !existsSync(join(path, "scripts", "capture-deployment-tests.mts"))) return false;
  try { return JSON.parse(readFileSync(join(path, "package.json"), "utf8")).name === "terminal-gothic-deploy"; }
  catch { return false; }
}

export function resolve_deployment_root(applicationRoot, environment = process.env) {
  const configured = environment.HSON_DEPLOY_ROOT?.trim();
  const candidates = [configured, resolve(applicationRoot, ".."), resolve(applicationRoot, "..", "hson-deploy")].filter(Boolean);
  const deploymentRoot = candidates.find(is_deployment_root);
  if (deploymentRoot === undefined) {
    throw new Error("PACK_DEPLOYMENT_WORKSPACE_NOT_FOUND: set HSON_DEPLOY_ROOT to the clean hson-deploy workspace");
  }
  return resolve(deploymentRoot);
}

export function canonical_package_locations(deploymentRoot) {
  const root = resolve(deploymentRoot);
  return Object.freeze({
    workRoot: join(root, ".deployment-work"),
    explorerArtifact: join(root, "static-production"),
  });
}

export function parse_json_output(output, label) {
  for (let index = output.indexOf("{"); index >= 0; index = output.indexOf("{", index + 1)) {
    try { return JSON.parse(output.slice(index)); }
    catch { /* npm may have printed a command banner before the final JSON value. */ }
  }
  throw new Error(`PACK_${label}_OUTPUT_INVALID`);
}

export function last_output_line(output, label) {
  const line = output.trim().split(/\r?\n/).at(-1)?.trim();
  if (!line) throw new Error(`PACK_${label}_OUTPUT_MISSING`);
  return line;
}

export function run_command(command, arguments_, options = {}) {
  const output = execFileSync(command, arguments_, {
    cwd: options.cwd,
    env: options.env,
    encoding: "utf8",
    stdio: ["inherit", "pipe", "inherit"],
  });
  if (output) process.stdout.write(output);
  return output;
}

function npm(run, cwd, arguments_, environment = process.env) {
  return run("npm", arguments_, { cwd, env: environment });
}

export function run_selected_tests({ applicationRoot, arguments_: selection, run = run_command }) {
  console.log("stage: selected-tests");
  const output = npm(run, applicationRoot, ["run", "test:canonical-node", "--", ...selection]);
  console.log("pass: selected tests completed");
  return output;
}

export function provision_local_frozen_evidence({ applicationRoot, explorerArtifact, publicRoot }) {
  if (!/^\/test-evidence\/[0-9a-f]{40}$/.test(publicRoot)) throw new Error("PACK_LOCAL_EVIDENCE_ROOT_INVALID");
  const evidenceDirectory = resolve(explorerArtifact, publicRoot.slice(1));
  if (!existsSync(join(evidenceDirectory, "index.json"))) throw new Error("PACK_LOCAL_EVIDENCE_INDEX_MISSING");
  const environmentFile = join(applicationRoot, ".env.frozen-local.local");
  writeFileSync(environmentFile, [
    "# Generated by npm run pack. Do not edit.",
    `VITE_TEST_EVIDENCE_ROOT=${publicRoot}`,
    `HSON_LOCAL_FROZEN_EVIDENCE_DIRECTORY=${evidenceDirectory}`,
    "",
  ].join("\n"));
  return Object.freeze({ environmentFile, publicRoot, evidenceDirectory });
}

function capture_metadata(candidate) {
  const capture = join(resolve(candidate), "capture");
  const path = join(capture, "capture-metadata.json");
  if (!existsSync(path)) throw new Error(`PACK_CAPTURE_METADATA_MISSING:${candidate}`);
  const cleanupPath = join(capture, "capture-cleanup.json");
  if (!existsSync(cleanupPath)) throw new Error(`PACK_CAPTURE_CLEANUP_MISSING:${candidate}`);
  return Object.freeze({
    capture,
    path,
    value: JSON.parse(readFileSync(path, "utf8")),
    cleanup: JSON.parse(readFileSync(cleanupPath, "utf8")),
  });
}

function same_json(left, right) {
  return JSON.stringify(left) === JSON.stringify(right);
}

/** Bind an already-executed certification capture to a fresh normal capture. */
export function combine_certification_capture({ deploymentRoot, normalCandidate, certificationCandidate }) {
  const normal = capture_metadata(normalCandidate);
  const certification = capture_metadata(certificationCandidate);
  if (!same_json(normal.value.selectedStages, ["semantic", "browser"])) throw new Error("PACK_NORMAL_CAPTURE_STAGE_MISMATCH");
  if (!same_json(certification.value.selectedStages, ["certification"])) throw new Error("PACK_CERTIFICATION_CAPTURE_STAGE_MISMATCH");
  if (!same_json(normal.value.deployment, certification.value.deployment)) throw new Error("PACK_CERTIFICATION_DEPLOYMENT_MISMATCH");
  if (certification.value.selection?.certification === undefined || certification.value.runs?.certification === undefined) {
    throw new Error("PACK_CERTIFICATION_CAPTURE_METADATA_INCOMPLETE");
  }
  if (!existsSync(join(certification.capture, "certification.json"))) throw new Error("PACK_CERTIFICATION_REPORT_MISSING");

  const workRoot = canonical_package_locations(deploymentRoot).workRoot;
  mkdirSync(workRoot, { recursive: true });
  const combined = join(workRoot, `capture-certified-${Date.now().toString(36)}-${crypto.randomUUID()}`);
  cpSync(resolve(normalCandidate), combined, { recursive: true, errorOnExist: true });
  copyFileSync(join(certification.capture, "certification.json"), join(combined, "capture", "certification.json"));
  const metadata = {
    ...normal.value,
    selectedStages: ["semantic", "browser", "certification"],
    selection: { ...normal.value.selection, certification: certification.value.selection?.certification },
    observedStages: [...(certification.value.observedStages ?? []), ...(normal.value.observedStages ?? [])],
    timeline: [...(certification.value.timeline ?? []), ...(normal.value.timeline ?? [])],
    runs: { ...normal.value.runs, certification: certification.value.runs?.certification },
  };
  const metadataPath = join(combined, "capture", "capture-metadata.json");
  const temporary = `${metadataPath}.${crypto.randomUUID()}.tmp`;
  writeFileSync(temporary, `${JSON.stringify(metadata, null, 2)}\n`, { flag: "wx" });
  renameSync(temporary, metadataPath);
  const cleanupPath = join(combined, "capture", "capture-cleanup.json");
  const cleanupTemporary = `${cleanupPath}.${crypto.randomUUID()}.tmp`;
  writeFileSync(cleanupTemporary, `${JSON.stringify({ captures: { normal: normal.cleanup, certification: certification.cleanup } }, null, 2)}\n`, { flag: "wx" });
  renameSync(cleanupTemporary, cleanupPath);
  return combined;
}

export function execute_pack({ deploymentRoot, applicationRoot, run = run_command, environment = process.env, certificationCandidate, combineCapture = combine_certification_capture }) {
  const locations = canonical_package_locations(deploymentRoot);
  const verifiedEnvironment = applicationRoot === undefined
    ? environment
    : { ...environment, HSON_INVOKING_APPLICATION_ROOT: resolve(applicationRoot) };
  let stage = PACK_STAGES[0];
  let captureCandidate;
  let evidencePackage;
  try {
    console.log(`stage: ${stage}`);
    npm(run, deploymentRoot, ["run", "verify"], verifiedEnvironment);

    stage = PACK_STAGES[1];
    console.log(`stage: ${stage}`);
    npm(run, deploymentRoot, ["-w", "hson-live", "run", "build"], verifiedEnvironment);

    stage = PACK_STAGES[2];
    console.log(`stage: ${stage}`);
    npm(run, deploymentRoot, ["run", "verify:package-surface"], verifiedEnvironment);

    stage = PACK_STAGES[3];
    console.log(`stage: ${stage}`);
    const normalCandidate = last_output_line(npm(run, deploymentRoot, ["run", "capture:deployment-tests:normal"], verifiedEnvironment), "CAPTURE");
    captureCandidate = normalCandidate;
    if (certificationCandidate !== undefined) {
      stage = "bind-certification-evidence";
      console.log(`stage: ${stage}`);
      captureCandidate = combineCapture({ deploymentRoot, normalCandidate, certificationCandidate });
    }

    stage = PACK_STAGES[4];
    console.log(`stage: ${stage}`);
    const materialized = parse_json_output(npm(run, deploymentRoot, ["run", "materialize:test-evidence", "--", captureCandidate], verifiedEnvironment), "MATERIALIZATION");
    evidencePackage = materialized.candidate;
    if (typeof evidencePackage !== "string" || !/^\/test-evidence\/[0-9a-f]{40}$/.test(materialized.publicRoot) || !/^[0-9a-f]{64}$/.test(materialized.artifactSetSha256)) throw new Error("PACK_MATERIALIZATION_CONTRACT_INVALID");
    const acceptanceFile = join(evidencePackage, "accepted.json");

    stage = PACK_STAGES[5];
    console.log(`stage: ${stage}`);
    npm(run, deploymentRoot, ["run", "prepare:static-production"], {
      ...verifiedEnvironment,
      VITE_TEST_EVIDENCE_ROOT: materialized.publicRoot,
      TEST_EVIDENCE_ACCEPTANCE_FILE: acceptanceFile,
    });
    const localEvidence = applicationRoot === undefined
      ? undefined
      : provision_local_frozen_evidence({ applicationRoot, explorerArtifact: locations.explorerArtifact, publicRoot: materialized.publicRoot });

    const result = Object.freeze({
      pass: true,
      stage: "complete",
      outputDirectory: locations.explorerArtifact,
      explorerArtifact: locations.explorerArtifact,
      evidencePackage,
      acceptanceFile,
      captureCandidate,
      evidenceRoot: materialized.publicRoot,
      artifactSetSha256: materialized.artifactSetSha256,
      ...(localEvidence === undefined ? {} : { localEvidence }),
    });
    console.log(JSON.stringify(result, null, 2));
    return result;
  } catch (cause) {
    const failure = Object.freeze({
      pass: false,
      stage,
      outputDirectory: locations.explorerArtifact,
      evidencePackage: evidencePackage ?? null,
      failureLocation: evidencePackage ?? captureCandidate ?? locations.workRoot,
    });
    console.error(JSON.stringify(failure, null, 2));
    throw cause;
  }
}

export function write_certification_receipt(result, completedAt = new Date().toISOString()) {
  const receiptPath = join(result.explorerArtifact, CERTIFICATION_RECEIPT);
  const receipt = Object.freeze({
    schemaVersion: 1,
    kind: "hson-tests-explorer-certification",
    certified: true,
    completedAt,
    authority: CERTIFICATION_AUTHORITY,
    evidenceRoot: result.evidenceRoot,
    deploymentCommit: result.evidenceRoot?.split("/").at(-1),
    evidenceArtifactSetSha256: result.artifactSetSha256,
  });
  writeFileSync(receiptPath, `${JSON.stringify(receipt, null, 2)}\n`, { flag: "wx" });
  return Object.freeze({ path: receiptPath, ...receipt });
}

export function execute_certification(options) {
  const run = options.run ?? run_command;
  const environment = options.environment ?? process.env;
  const locations = canonical_package_locations(options.deploymentRoot);
  const verifiedEnvironment = options.applicationRoot === undefined
    ? environment
    : { ...environment, HSON_INVOKING_APPLICATION_ROOT: resolve(options.applicationRoot) };
  let stage = "verify-source";
  let certificationCandidate;
  try {
    console.log(`stage: ${stage}`);
    npm(run, options.deploymentRoot, ["run", "verify"], verifiedEnvironment);
    stage = "certification-authority";
    console.log(`stage: ${stage}`);
    certificationCandidate = last_output_line(npm(run, options.deploymentRoot, ["run", "capture:deployment-tests:certification"], verifiedEnvironment), "CERTIFICATION_CAPTURE");
  } catch (cause) {
    console.error(JSON.stringify({ pass: false, stage, outputDirectory: locations.explorerArtifact, evidencePackage: null, failureLocation: locations.workRoot }, null, 2));
    throw cause;
  }
  const packed = execute_pack({ ...options, certificationCandidate });
  const receipt = (options.writeReceipt ?? write_certification_receipt)(packed);
  const result = Object.freeze({ ...packed, certified: true, certificationCaptureCandidate: certificationCandidate, certificationReceipt: receipt });
  console.log(JSON.stringify(result, null, 2));
  return result;
}

export function inspect_report(path) {
  const absolute = resolve(path);
  const value = JSON.parse(readFileSync(absolute, "utf8"));
  const result = value.run && value.summary
    ? { pass: value.run.status === "passed", stage: value.run.status, report: absolute, summary: value.summary }
    : value.accepted === true
      ? { pass: true, stage: "materialized", report: absolute, evidencePackage: dirname(absolute), evidenceRoot: value.evidenceRoot }
      : { pass: (value.categories ?? []).every((category) => category.status === "passed"), stage: "frozen-index", report: absolute, categories: value.categories?.map((category) => ({ id: category.id, status: category.status })) };
  console.log(JSON.stringify(result, null, 2));
  return result;
}

function usage() {
  console.error("usage: certified-package <run [selection]|pack|certify|location|inspect <json-file>>");
  process.exitCode = 2;
}

export function main(arguments_ = process.argv.slice(2), environment = process.env) {
  const applicationRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
  const [command, ...rest] = arguments_;
  if (command === "run") return run_selected_tests({ applicationRoot, arguments_: rest });
  if (command === "inspect" && rest.length === 1) return inspect_report(rest[0]);
  if (command === "pack" || command === "certify" || command === "location") {
    const deploymentRoot = resolve_deployment_root(applicationRoot, environment);
    if (command === "location") {
      const result = canonical_package_locations(deploymentRoot);
      console.log(JSON.stringify(result, null, 2));
      return result;
    }
    const options = { deploymentRoot, applicationRoot, environment };
    return command === "pack" ? execute_pack(options) : execute_certification(options);
  }
  usage();
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try { main(); }
  catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
