import { hson } from "hson-live";
import type { TestSuite } from "../../harness/core/test-contracts";
import { read_case, throwCase, commitCase } from "./handle-helpers";



export function livemap_suites_handle_2(): TestSuite {
  const SUITE = "livemap/handle/level-2";

  return {
    suite: SUITE,
    cases: [
      read_case({
        suite: SUITE,
        caseId: "handle-array.first-returns-first-item", name: "handle array.first returns first item",
        input: { items: ["a", "b", "c"] },
        act: (map) => map.at(["items"]).array.first(),
        expected: "a",
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-array.last-returns-last-item", name: "handle array.last returns last item",
        input: { items: ["a", "b", "c"] },
        act: (map) => map.at(["items"]).array.last(),
        expected: "c",
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-array.first-on-empty-array-throws", name: "handle array.first on empty array throws",
        input: { items: [] },
        act: (map) => map.at(["items"]).array.first(),
        expectedMessage: "LiveMap array index does not resolve: [\"items\"][0]",
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-array.last-on-empty-array-throws", name: "handle array.last on empty array throws",
        input: { items: [] },
        act: (map) => map.at(["items"]).array.last(),
        expectedMessage: "LiveMap array index does not resolve: [\"items\"][-1]",
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-array.first-on-non-array-throws", name: "handle array.first on non-array throws",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).array.first(),
        expectedMessage: "LiveMap path is not an array: [\"user\"]",
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-array.last-on-non-array-throws", name: "handle array.last on non-array throws",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).array.last(),
        expectedMessage: "LiveMap path is not an array: [\"user\"]",
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-array.includes-returns-true-for-primitive-item", name: "handle array.includes returns true for primitive item",
        input: { items: ["a", "b", "c"] },
        act: (map) => map.at(["items"]).array.includes("b"),
        expected: true,
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-array.includes-returns-false-for-missing-primitive-item", name: "handle array.includes returns false for missing primitive item",
        input: { items: ["a", "b", "c"] },
        act: (map) => map.at(["items"]).array.includes("x"),
        expected: false,
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-array.includes-rejects-reordered-object-entries", name: "handle array.includes rejects reordered object entries",
        input: { items: [{ name: "Ada", role: "user" }] },
        act: (map) => map.at(["items"]).array.includes({ role: "user", name: "Ada" }),
        expected: false,
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-array.includes-uses-deep-array-equality", name: "handle array.includes uses deep array equality",
        input: { items: [[0, 1], [2, 3]] },
        act: (map) => map.at(["items"]).array.includes([2, 3]),
        expected: true,
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-array.includes-on-non-array-throws", name: "handle array.includes on non-array throws",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).array.includes("Ada"),
        expectedMessage: "LiveMap path is not an array: [\"user\"]",
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-array.includes-rejects-non-json-value", name: "handle array.includes rejects non-JSON value",
        input: { items: [] },
        act: (map) => map.at(["items"]).array.includes(undefined as never),
        expectedMessage: "LiveMap value is not JSON at [\"items\"]",
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-array.indexof-returns-primitive-item-index", name: "handle array.indexOf returns primitive item index",
        input: { items: ["a", "b", "c"] },
        act: (map) => map.at(["items"]).array.indexOf("b"),
        expected: 1,
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-array.indexof-returns-1-for-missing-primitive-item", name: "handle array.indexOf returns -1 for missing primitive item",
        input: { items: ["a", "b", "c"] },
        act: (map) => map.at(["items"]).array.indexOf("x"),
        expected: -1,
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-array.indexof-rejects-reordered-object-entries", name: "handle array.indexOf rejects reordered object entries",
        input: { items: [{ name: "Ada", role: "user" }] },
        act: (map) => map.at(["items"]).array.indexOf({ role: "user", name: "Ada" }),
        expected: -1,
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-array.indexof-uses-deep-array-equality", name: "handle array.indexOf uses deep array equality",
        input: { items: [[0, 1], [2, 3]] },
        act: (map) => map.at(["items"]).array.indexOf([2, 3]),
        expected: 1,
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-array.indexof-on-non-array-throws", name: "handle array.indexOf on non-array throws",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).array.indexOf("Ada"),
        expectedMessage: "LiveMap path is not an array: [\"user\"]",
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-array.indexof-rejects-non-json-value", name: "handle array.indexOf rejects non-JSON value",
        input: { items: [] },
        act: (map) => map.at(["items"]).array.indexOf(undefined as never),
        expectedMessage: "LiveMap value is not JSON at [\"items\"]",
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-array.toarray-returns-array-copy", name: "handle array.toArray returns array copy",
        input: { items: [0, 1, 2] },
        act: (map) => map.at(["items"]).array.toArray(),
        expected: [0, 1, 2],
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-array.toarray-on-non-array-throws", name: "handle array.toArray on non-array throws",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).array.toArray(),
        expectedMessage: "LiveMap path is not an array: [\"user\"]",
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-object.toobject-returns-object-copy", name: "handle object.toObject returns object copy",
        input: { user: { name: "Ada", role: "user" } },
        act: (map) => map.at(["user"]).object.toObject(),
        expected: { name: "Ada", role: "user" },
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-object.toobject-on-non-object-throws", name: "handle object.toObject on non-object throws",
        input: { items: [0, 1] },
        act: (map) => map.at(["items"]).object.toObject(),
        expectedMessage: "LiveMap path is not an object: [\"items\"]",
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-array.isempty-returns-true-for-empty-array", name: "handle array.isEmpty returns true for empty array",
        input: { items: [] },
        act: (map) => map.at(["items"]).array.isEmpty(),
        expected: true,
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-array.isempty-returns-false-for-populated-array", name: "handle array.isEmpty returns false for populated array",
        input: { items: [0, 1] },
        act: (map) => map.at(["items"]).array.isEmpty(),
        expected: false,
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-array.isempty-on-non-array-throws", name: "handle array.isEmpty on non-array throws",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).array.isEmpty(),
        expectedMessage: "LiveMap path is not an array: [\"user\"]",
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-object.isempty-returns-true-for-empty-object", name: "handle object.isEmpty returns true for empty object",
        input: { user: {} },
        act: (map) => map.at(["user"]).object.isEmpty(),
        expected: true,
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-object.isempty-returns-false-for-populated-object", name: "handle object.isEmpty returns false for populated object",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).object.isEmpty(),
        expected: false,
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-object.isempty-on-non-object-throws", name: "handle object.isEmpty on non-object throws",
        input: { items: [0, 1] },
        act: (map) => map.at(["items"]).object.isEmpty(),
        expectedMessage: "LiveMap path is not an object: [\"items\"]",
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-object.size-returns-property-count", name: "handle object.size returns property count",
        input: { user: { name: "Ada", role: "user" } },
        act: (map) => map.at(["user"]).object.size(),
        expected: 2,
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-object.size-returns-zero-for-empty-object", name: "handle object.size returns zero for empty object",
        input: { user: {} },
        act: (map) => map.at(["user"]).object.size(),
        expected: 0,
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-object.size-on-non-object-throws", name: "handle object.size on non-object throws",
        input: { items: [0, 1] },
        act: (map) => map.at(["items"]).object.size(),
        expectedMessage: "LiveMap path is not an object: [\"items\"]",
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-object.getkey-returns-property-value", name: "handle object.getKey returns property value",
        input: { user: { name: "Ada", age: 37 } },
        act: (map) => map.at(["user"]).object.getKey("name"),
        expected: "Ada",
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-object.getkey-returns-undefined-for-missing-property", name: "handle object.getKey returns undefined for missing property",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).object.getKey("role"),
        expected: undefined,
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-object.getkey-on-non-object-throws", name: "handle object.getKey on non-object throws",
        input: { items: [0, 1] },
        act: (map) => map.at(["items"]).object.getKey("name"),
        expectedMessage: "LiveMap path is not an object: [\"items\"]",
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-object.keys-returns-object-keys", name: "handle object.keys returns object keys",
        input: { user: { name: "Ada", role: "user" } },
        act: (map) => map.at(["user"]).object.keys(),
        expected: ["name", "role"],
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-object.values-returns-object-values", name: "handle object.values returns object values",
        input: { user: { name: "Ada", role: "user" } },
        act: (map) => map.at(["user"]).object.values(),
        expected: ["Ada", "user"],
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-object.entries-returns-object-entries", name: "handle object.entries returns object entries",
        input: { user: { name: "Ada", role: "user" } },
        act: (map) => map.at(["user"]).object.entries(),
        expected: [["name", "Ada"], ["role", "user"]],
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-array.at-supports-negative-index", name: "handle array.at supports negative index",
        input: { items: ["a", "b", "c"] },
        act: (map) => map.at(["items"]).array.at(-1),
        expected: "c",
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-array.slice-returns-sliced-copy", name: "handle array.slice returns sliced copy",
        input: { items: ["a", "b", "c", "d"] },
        act: (map) => map.at(["items"]).array.slice(1, 3),
        expected: ["b", "c"],
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-array.slice-supports-negative-start", name: "handle array.slice supports negative start",
        input: { items: ["a", "b", "c", "d"] },
        act: (map) => map.at(["items"]).array.slice(-2),
        expected: ["c", "d"],
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-array.slice-on-non-array-throws", name: "handle array.slice on non-array throws",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).array.slice(0, 1),
        expectedMessage: "LiveMap path is not an array: [\"user\"]",
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-array.take-drop-takelast-droplast-read-expected-slices", name: "handle array.take/drop/takeLast/dropLast read expected slices",
        input: { items: ["a", "b", "c", "d"] },
        act: (map) => ({
          take: map.at(["items"]).array.take(2),
          drop: map.at(["items"]).array.drop(2),
          takeLast: map.at(["items"]).array.takeLast(2),
          dropLast: map.at(["items"]).array.dropLast(2),
        }),
        expected: {
          take: ["a", "b"],
          drop: ["c", "d"],
          takeLast: ["c", "d"],
          dropLast: ["a", "b"],
        },
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-array.at-reads-object-item", name: "handle array.at reads object item",
        input: { items: [{ id: "a", count: 1 }, { id: "b", count: 2 }] },
        act: (map) => map.at(["items"]).array.at(1),
        expected: { id: "b", count: 2 },
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-array.first-last-read-object-items", name: "handle array.first/last read object items",
        input: { items: [{ id: "a", count: 1 }, { id: "b", count: 2 }] },
        act: (map) => ({
          first: map.at(["items"]).array.first(),
          last: map.at(["items"]).array.last(),
        }),
        expected: {
          first: { id: "a", count: 1 },
          last: { id: "b", count: 2 },
        },
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-array.slice-reads-object-item-slice", name: "handle array.slice reads object item slice",
        input: { items: [{ id: "a", count: 1 }, { id: "b", count: 2 }, { id: "c", count: 3 }] },
        act: (map) => map.at(["items"]).array.slice(1),
        expected: [{ id: "b", count: 2 }, { id: "c", count: 3 }],
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-array.take-rejects-negative-count", name: "handle array.take rejects negative count",
        input: { items: ["a", "b"] },
        act: (map) => map.at(["items"]).array.take(-1),
        expectedMessage: "LiveMap array count is not valid at [\"items\"]: -1",
      }),
      commitCase({
        suite: SUITE,
        caseId: "handle-array.pushmany-appends-items", name: "handle array.pushMany appends items",
        input: { items: [0, 1] },
        act: (map) => map.at(["items"]).array.pushMany([2, 3]),
        expectedChanged: true,
        expectedOps: [
          { kind: "splice", path: ["items"], start: 2, removed: [], inserted: [2, 3], prev: [0, 1], next: [0, 1, 2, 3] }
        ],
        expectedRoot: { items: [0, 1, 2, 3] },
      }),
      commitCase({
        suite: SUITE,
        caseId: "handle-array.unshiftmany-prepends-items", name: "handle array.unshiftMany prepends items",
        input: { items: [2, 3] },
        act: (map) => map.at(["items"]).array.unshiftMany([0, 1]),
        expectedChanged: true,
        expectedOps: [
          { kind: "splice", path: ["items"], start: 0, removed: [], inserted: [0, 1], prev: [2, 3], next: [0, 1, 2, 3] }
        ],
        expectedRoot: { items: [0, 1, 2, 3] },
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-array.pushmany-rejects-non-array-values", name: "handle array.pushMany rejects non-array values",
        input: { items: [] },
        act: (map) => map.at(["items"]).array.pushMany(1 as never),
        expectedMessage: "LiveMap array values are not an array at [\"items\"]",
      }),
      commitCase({
        suite: SUITE,
        caseId: "handle-array.reverse-reverses-items", name: "handle array.reverse reverses items",
        input: { items: [0, 1, 2] },
        act: (map) => map.at(["items"]).array.reverse(),
        expectedChanged: true,
        expectedOps: [
          { kind: "set", path: ["items"], prev: [0, 1, 2], next: [2, 1, 0] },
        ],
        expectedRoot: { items: [2, 1, 0] },
      }),
      commitCase({
        suite: SUITE,
        caseId: "handle-array.sortnumbers-sorts-ascending-by-default", name: "handle array.sortNumbers sorts ascending by default",
        input: { items: [3, 1, 2] },
        act: (map) => map.at(["items"]).array.sortNumbers(),
        expectedChanged: true,
        expectedOps: [
          { kind: "set", path: ["items"], prev: [3, 1, 2], next: [1, 2, 3] },
        ],
        expectedRoot: { items: [1, 2, 3] },
      }),
      commitCase({
        suite: SUITE,
        caseId: "handle-array.sortnumbers-sorts-descending", name: "handle array.sortNumbers sorts descending",
        input: { items: [3, 1, 2] },
        act: (map) => map.at(["items"]).array.sortNumbers("desc"),
        expectedChanged: true,
        expectedOps: [
          { kind: "set", path: ["items"], prev: [3, 1, 2], next: [3, 2, 1] },
        ],
        expectedRoot: { items: [3, 2, 1] },
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-array.sortnumbers-rejects-non-number-item", name: "handle array.sortNumbers rejects non-number item",
        input: { items: [1, "2", 3] },
        act: (map) => map.at(["items"]).array.sortNumbers(),
        expectedMessage: "LiveMap array contains a non-number item at [\"items\"]",
      }),
      commitCase({
        suite: SUITE,
        caseId: "handle-array.sortstrings-sorts-ascending-by-default", name: "handle array.sortStrings sorts ascending by default",
        input: { items: ["c", "a", "b"] },
        act: (map) => map.at(["items"]).array.sortStrings(),
        expectedChanged: true,
        expectedOps: [
          { kind: "set", path: ["items"], prev: ["c", "a", "b"], next: ["a", "b", "c"] },
        ],
        expectedRoot: { items: ["a", "b", "c"] },
      }),
      commitCase({
        suite: SUITE,
        caseId: "handle-array.sortstrings-sorts-descending", name: "handle array.sortStrings sorts descending",
        input: { items: ["c", "a", "b"] },
        act: (map) => map.at(["items"]).array.sortStrings("desc"),
        expectedChanged: true,
        expectedOps: [
          { kind: "set", path: ["items"], prev: ["c", "a", "b"], next: ["c", "b", "a"] },
        ],
        expectedRoot: { items: ["c", "b", "a"] },
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-array.sortstrings-rejects-non-string-item", name: "handle array.sortStrings rejects non-string item",
        input: { items: ["a", 2, "c"] },
        act: (map) => map.at(["items"]).array.sortStrings(),
        expectedMessage: "LiveMap array contains a non-string item at [\"items\"]",
      }),
      commitCase({
        suite: SUITE,
        caseId: "handle-array.splice-removes-and-inserts-items", name: "handle array.splice removes and inserts items",
        input: { items: [0, 1, 2, 3] },
        act: (map) => map.at(["items"]).array.splice(1, 2, "x"),
        expectedChanged: true,
        expectedOps: [
          { kind: "splice", path: ["items"], start: 1, removed: [1, 2], inserted: ["x"], prev: [0, 1, 2, 3], next: [0, "x", 3] },
        ],
        expectedRoot: { items: [0, "x", 3] },
      }),
      commitCase({
        suite: SUITE,
        caseId: "handle-array.splice-supports-negative-start", name: "handle array.splice supports negative start",
        input: { items: [0, 1, 2, 3] },
        act: (map) => map.at(["items"]).array.splice(-1, 1, "x"),
        expectedChanged: true,
        expectedOps: [
          { kind: "splice", path: ["items"], start: 3, removed: [3], inserted: ["x"], prev: [0, 1, 2, 3], next: [0, 1, 2, "x"] },
        ],
        expectedRoot: { items: [0, 1, 2, "x"] },
      }),
      commitCase({
        suite: SUITE,
        caseId: "handle-array.splice-with-start-only-removes-through-end", name: "handle array.splice with start only removes through end",
        input: { items: [0, 1, 2, 3] },
        act: (map) => map.at(["items"]).array.splice(2),
        expectedChanged: true,
        expectedOps: [
          { kind: "splice", path: ["items"], start: 2, removed: [2, 3], inserted: [], prev: [0, 1, 2, 3], next: [0, 1] }
        ],
        expectedRoot: { items: [0, 1] },
      }),
      commitCase({
        suite: SUITE,
        caseId: "handle-array.unique-removes-duplicate-values", name: "handle array.unique removes duplicate values",
        input: { items: [0, 1, 0, { name: "Ada" }, { name: "Ada" }] },
        act: (map) => map.at(["items"]).array.unique(),
        expectedChanged: true,
        expectedOps: [
          { kind: "set", path: ["items"], prev: [0, 1, 0, { name: "Ada" }, { name: "Ada" }], next: [0, 1, { name: "Ada" }] },
        ],
        expectedRoot: { items: [0, 1, { name: "Ada" }] },
      }),
      commitCase({
        suite: SUITE,
        caseId: "handle-array.removevalue-removes-first-matching-value", name: "handle array.removeValue removes first matching value",
        input: { items: ["a", "b", "a", "c"] },
        act: (map) => map.at(["items"]).array.removeValue("a"),
        expectedChanged: true,
        expectedOps: [
          { kind: "set", path: ["items"], prev: ["a", "b", "a", "c"], next: ["b", "a", "c"] },
        ],
        expectedRoot: { items: ["b", "a", "c"] },
      }),
      commitCase({
        suite: SUITE,
        caseId: "handle-array.removevalue-missing-value-unchanged", name: "handle array.removeValue missing value unchanged",
        input: { items: ["a", "b"] },
        act: (map) => map.at(["items"]).array.removeValue("x"),
        expectedChanged: false,
        expectedOps: [],
        expectedRoot: { items: ["a", "b"] },
      }),
      commitCase({
        suite: SUITE,
        caseId: "handle-array.removeall-removes-all-matching-values", name: "handle array.removeAll removes all matching values",
        input: { items: ["a", "b", "a", "c"] },
        act: (map) => map.at(["items"]).array.removeAll("a"),
        expectedChanged: true,
        expectedOps: [
          { kind: "set", path: ["items"], prev: ["a", "b", "a", "c"], next: ["b", "c"] },
        ],
        expectedRoot: { items: ["b", "c"] },
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-array.removeall-on-non-array-throws", name: "handle array.removeAll on non-array throws",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).array.removeAll("a"),
        expectedMessage: "LiveMap path is not an array: [\"user\"]",
      }),
      commitCase({
        suite: SUITE,
        caseId: "handle-array.insert-supports-negative-index", name: "handle array.insert supports negative index",
        input: { items: ["a", "b", "c"] },
        act: (map) => map.at(["items"]).array.insert(-1, "x"),
        expectedChanged: true,
        expectedOps: [
          { kind: "splice", path: ["items"], start: 2, removed: [], inserted: ["x"], prev: ["a", "b", "c"], next: ["a", "b", "x", "c"] }
        ],
        expectedRoot: { items: ["a", "b", "x", "c"] },
      }),
      commitCase({
        suite: SUITE,
        caseId: "handle-array.remove-supports-negative-index", name: "handle array.remove supports negative index",
        input: { items: ["a", "b", "c"] },
        act: (map) => map.at(["items"]).array.remove(-1),
        expectedChanged: true,
        expectedOps: [
          { kind: "splice", path: ["items"], start: 2, removed: ["c"], inserted: [], prev: ["a", "b", "c"], next: ["a", "b"] }
        ],
        expectedRoot: { items: ["a", "b"] },
      }),
      commitCase({
        suite: SUITE,
        caseId: "handle-array.replace-supports-negative-index", name: "handle array.replace supports negative index",
        input: { items: ["a", "b", "c"] },
        act: (map) => map.at(["items"]).array.replace(-1, "x"),
        expectedChanged: true,
        expectedOps: [
          { kind: "splice", path: ["items"], start: 2, removed: ["c"], inserted: ["x"], prev: ["a", "b", "c"], next: ["a", "b", "x"] }
        ],
        expectedRoot: { items: ["a", "b", "x"] },
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-array.move-rejects-negative-from-index", name: "handle array.move rejects negative from index",
        input: { items: ["a", "b", "c"] },
        act: (map) => map.at(["items"]).array.move(-1, 0),
        expectedMessage: "Invalid LiveMap projected move at [\"items\"]: source index -1 does not resolve in the staged array",
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-array.slice-rejects-non-integer-start", name: "handle array.slice rejects non-integer start",
        input: { items: [0, 1, 2] },
        act: (map) => map.at(["items"]).array.slice(1.5),
        expectedMessage: "LiveMap array slice start is not a valid index at [\"items\"]: 1.5",
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-array.slice-rejects-non-integer-end", name: "handle array.slice rejects non-integer end",
        input: { items: [0, 1, 2] },
        act: (map) => map.at(["items"]).array.slice(0, 1.5),
        expectedMessage: "LiveMap array slice end is not a valid index at [\"items\"]: 1.5",
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-array.splice-rejects-non-integer-start", name: "handle array.splice rejects non-integer start",
        input: { items: [0, 1, 2] },
        act: (map) => map.at(["items"]).array.splice(1.5),
        expectedMessage: "LiveMap array splice start is not a valid index at [\"items\"]: 1.5",
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-array.splice-rejects-negative-deletecount", name: "handle array.splice rejects negative deleteCount",
        input: { items: [0, 1, 2] },
        act: (map) => map.at(["items"]).array.splice(1, -1),
        expectedMessage: "LiveMap array splice deleteCount is not valid at [\"items\"]: -1",
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-array.splice-rejects-non-integer-deletecount", name: "handle array.splice rejects non-integer deleteCount",
        input: { items: [0, 1, 2] },
        act: (map) => map.at(["items"]).array.splice(1, 1.5),
        expectedMessage: "LiveMap array splice deleteCount is not valid at [\"items\"]: 1.5",
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-object.pick-returns-selected-keys", name: "handle object.pick returns selected keys",
        input: { user: { name: "Ada", role: "user", active: true } },
        act: (map) => map.at(["user"]).object.pick(["name", "active"]),
        expected: { name: "Ada", active: true },
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-object.pick-ignores-missing-keys", name: "handle object.pick ignores missing keys",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).object.pick(["name", "role"]),
        expected: { name: "Ada" },
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-object.omit-removes-selected-keys", name: "handle object.omit removes selected keys",
        input: { user: { name: "Ada", role: "user", active: true } },
        act: (map) => map.at(["user"]).object.omit(["role"]),
        expected: { name: "Ada", active: true },
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-object.pick-rejects-non-array-keys", name: "handle object.pick rejects non-array keys",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).object.pick("name" as never),
        expectedMessage: "LiveMap object keys are not an array at [\"user\"]",
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-object.omit-rejects-non-string-key", name: "handle object.omit rejects non-string key",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).object.omit([0 as never]),
        expectedMessage: "LiveMap object key is not a string at [\"user\"]",
      }),
      commitCase({
        suite: SUITE,
        caseId: "handle-object.deletemany-deletes-selected-keys", name: "handle object.deleteMany deletes selected keys",
        input: { user: { name: "Ada", role: "user", active: true } },
        act: (map) => map.at(["user"]).object.deleteMany(["role", "active"]),
        expectedChanged: true,
        expectedOps: [
          { kind: "delete", path: ["user", "role"], prev: "user", next: undefined },
          { kind: "delete", path: ["user", "active"], prev: true, next: undefined },
        ],
        expectedRoot: { user: { name: "Ada" } },
      }),
      commitCase({
        suite: SUITE,
        caseId: "handle-object.deletemany-ignores-missing-keys", name: "handle object.deleteMany ignores missing keys",
        input: { user: { name: "Ada" } },
        act: (map) => map.at(["user"]).object.deleteMany(["role"]),
        expectedChanged: false,
        expectedOps: [],
        expectedRoot: { user: { name: "Ada" } },
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-object.deletemany-on-non-object-repeated-invocation-throws", name: "handle object.deleteMany on non-object repeated invocation throws",
        input: { items: [0, 1] },
        act: (map) => map.at(["items"]).object.deleteMany(["name"]),
        expectedMessage: "LiveMap path is not an object: [\"items\"]",
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-object.deletemany-on-non-object-throws", name: "handle object.deleteMany on non-object throws",
        input: { items: [0, 1] },
        act: (map) => map.at(["items"]).object.deleteMany(["name"]),
        expectedMessage: "LiveMap path is not an object: [\"items\"]",
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-array.sortnumbers-rejects-invalid-direction", name: "handle array.sortNumbers rejects invalid direction",
        input: { items: [3, 1, 2] },
        act: (map) => map.at(["items"]).array.sortNumbers("sideways" as never),
        expectedMessage: "LiveMap array sort direction is not valid at [\"items\"]: sideways",
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-array.sortstrings-rejects-invalid-direction", name: "handle array.sortStrings rejects invalid direction",
        input: { items: ["c", "a", "b"] },
        act: (map) => map.at(["items"]).array.sortStrings("sideways" as never),
        expectedMessage: "LiveMap array sort direction is not valid at [\"items\"]: sideways",
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-object.pick-on-non-object-throws", name: "handle object.pick on non-object throws",
        input: { items: [0, 1] },
        act: (map) => map.at(["items"]).object.pick(["name"]),
        expectedMessage: "LiveMap path is not an object: [\"items\"]",
      }),
      throwCase({
        suite: SUITE,
        caseId: "handle-object.omit-on-non-object-throws", name: "handle object.omit on non-object throws",
        input: { items: [0, 1] },
        act: (map) => map.at(["items"]).object.omit(["name"]),
        expectedMessage: "LiveMap path is not an object: [\"items\"]",
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-object.pick-with-empty-keys-returns-empty-object", name: "handle object.pick with empty keys returns empty object",
        input: { user: { name: "Ada", role: "user" } },
        act: (map) => map.at(["user"]).object.pick([]),
        expected: {},
      }),
      read_case({
        suite: SUITE,
        caseId: "handle-object.omit-with-empty-keys-returns-object-copy", name: "handle object.omit with empty keys returns object copy",
        input: { user: { name: "Ada", role: "user" } },
        act: (map) => map.at(["user"]).object.omit([]),
        expected: { name: "Ada", role: "user" },
      }),
      commitCase({
        suite: SUITE,
        caseId: "handle-object.deletemany-with-duplicate-keys-emits-one-delete-op", name: "handle object.deleteMany with duplicate keys emits one delete op",
        input: { user: { name: "Ada", role: "user" } },
        act: (map) => map.at(["user"]).object.deleteMany(["role", "role"]),
        expectedChanged: true,
        expectedOps: [
          { kind: "delete", path: ["user", "role"], prev: "user", next: undefined },
        ],
        expectedRoot: { user: { name: "Ada" } },
      }),


    ] as const,
  };
}
