/* Generated by Hson Schema hson-schema-mvp-6. Do not edit. */
import type { HsonCanonical } from "hson-live/hson";
abstract class __DEMO_LIVEMAP_SCHEMARootM0M1ArrayProof0 { declare private readonly __hsonSchemaProof0: void; }
abstract class __DEMO_LIVEMAP_SCHEMARootM0ObjectProof1 { declare private readonly __hsonSchemaProof1: void; }
abstract class __DEMO_LIVEMAP_SCHEMARootObjectProof2 { declare private readonly __hsonSchemaProof2: void; }
abstract class __DEMO_LIVEMAP_SCHEMAHsonProof3 { declare private readonly __hsonSchemaProof3: void; }
export type DEMO_LIVEMAP_SCHEMAType = Readonly<{ readonly ui: Readonly<{ readonly currentView: (string) | (null); readonly activeWidgets: ReadonlyArray<string> & __DEMO_LIVEMAP_SCHEMARootM0M1ArrayProof0; }> & __DEMO_LIVEMAP_SCHEMARootM0ObjectProof1; }> & __DEMO_LIVEMAP_SCHEMARootObjectProof2;
export type DEMO_LIVEMAP_SCHEMAHson = HsonCanonical & __DEMO_LIVEMAP_SCHEMAHsonProof3;
