/* Generated by Hson Schema hson-schema-mvp-7. Do not edit. */
import type { HsonSchemaMutationCandidate } from "hson-live";
import type { HsonCanonical } from "hson-live/hson";
abstract class __DEMO_LIVEMAP_SCHEMAD0DefinitionProof0 { declare private readonly __hsonSchemaProof0: void; }
abstract class __DEMO_LIVEMAP_SCHEMAD1DefinitionProof1 { declare private readonly __hsonSchemaProof1: void; }
abstract class __DEMO_LIVEMAP_SCHEMARootM0M1ArrayProof2 { declare private readonly __hsonSchemaProof2: void; }
abstract class __DEMO_LIVEMAP_SCHEMARootM0ObjectProof3 { declare private readonly __hsonSchemaProof3: void; }
abstract class __DEMO_LIVEMAP_SCHEMARootObjectProof4 { declare private readonly __hsonSchemaProof4: void; }
abstract class __DEMO_LIVEMAP_SCHEMAHsonProof5 { declare private readonly __hsonSchemaProof5: void; }
type __DEMO_LIVEMAP_SCHEMADefinition0MutationCandidate = ("about") | (("test") | (("parse") | (("build") | (("bar-bar") | (("towl") | (("cells") | (("fleurs") | ("color-sudoku"))))))));
type __DEMO_LIVEMAP_SCHEMADefinition1MutationCandidate = ("point") | (("oklch") | ("bling"));
type __DEMO_LIVEMAP_SCHEMADefinition0 = (("about") | (("test") | (("parse") | (("build") | (("bar-bar") | (("towl") | (("cells") | (("fleurs") | ("color-sudoku"))))))))) & __DEMO_LIVEMAP_SCHEMAD0DefinitionProof0 & HsonSchemaMutationCandidate<__DEMO_LIVEMAP_SCHEMADefinition0MutationCandidate>;
type __DEMO_LIVEMAP_SCHEMADefinition1 = (("point") | (("oklch") | ("bling"))) & __DEMO_LIVEMAP_SCHEMAD1DefinitionProof1 & HsonSchemaMutationCandidate<__DEMO_LIVEMAP_SCHEMADefinition1MutationCandidate>;
export type DEMO_LIVEMAP_SCHEMAType = Readonly<{ readonly ui: Readonly<{ readonly currentView: (__DEMO_LIVEMAP_SCHEMADefinition0) | (null); readonly activeWidgets: ReadonlyArray<__DEMO_LIVEMAP_SCHEMADefinition1> & __DEMO_LIVEMAP_SCHEMARootM0M1ArrayProof2 & HsonSchemaMutationCandidate<Array<__DEMO_LIVEMAP_SCHEMADefinition1MutationCandidate>>; }> & __DEMO_LIVEMAP_SCHEMARootM0ObjectProof3 & HsonSchemaMutationCandidate<{ currentView: (__DEMO_LIVEMAP_SCHEMADefinition0MutationCandidate) | (null); activeWidgets: Array<__DEMO_LIVEMAP_SCHEMADefinition1MutationCandidate>; }>; }> & __DEMO_LIVEMAP_SCHEMARootObjectProof4 & HsonSchemaMutationCandidate<{ ui: { currentView: (__DEMO_LIVEMAP_SCHEMADefinition0MutationCandidate) | (null); activeWidgets: Array<__DEMO_LIVEMAP_SCHEMADefinition1MutationCandidate>; }; }>;
export type DEMO_LIVEMAP_SCHEMAHson = HsonCanonical & __DEMO_LIVEMAP_SCHEMAHsonProof5;
